/* Fiiiish Island service worker - GENERATED by scripts/make-sw.mjs. Do not edit.
   Built from 11 app cache tier(s). */
'use strict';

const BASE = "/island";
const SHELL_VERSION = 'fi-c83afe61';
const APP_VERS = {"rust":"be0f1b85","terraria":"945ed135","isaac":"d36d008a","dbd":"fa4b80fd","wardogs":"7b2028ae","poe2":"7f484990","elden":"417fc58c","_shared":"0668ca96","tarkov":"75eef9b0","clips":"8d87e20d","hq":"7dee59f6"};
const SPRITE_APPS = {"terraria":{"dir":"sprites","ver":"10530945"},"wardogs":{"dir":"sprites","ver":"b6d3d20a"},"poe2":{"dir":"sprites","ver":"81cb54bc"},"elden":{"dir":"sprites","ver":"3abbe25c"}};
const TILE_APPS = {"elden":{"dir":"map","ver":"3abbe25c"}};

const SHELL_CACHE = 'fi-shell-' + SHELL_VERSION;
const IMAGE_CACHE = 'fi-img-v1';
const OFFLINE_URL = BASE + '/offline/';
const IMAGE_LRU_MAX = 2000;

const PRECACHE = [
  "/island/",
  "/island/_astro/dbd.D4vV-_Ph.css",
  "/island/_astro/settings.Caj04qeE.css",
  "/island/clips/",
  "/island/dbd/",
  "/island/elden/",
  "/island/favicon.svg",
  "/island/icons/apple-touch-icon.png",
  "/island/icons/icon-192.png",
  "/island/icons/icon-maskable-192.png",
  "/island/icons/icon-maskable.svg",
  "/island/icons/icon.svg",
  "/island/import/",
  "/island/isaac/",
  "/island/manifest.webmanifest",
  "/island/offline/",
  "/island/poe2/",
  "/island/rust/",
  "/island/tarkov/",
  "/island/terraria/",
  "/island/wardogs/"
];

/* Each app's own route stylesheet, precached INTO THAT APP'S bucket at install
   - not into the shell. Install-time (not cache-on-first-fetch) so an installed
   phone still renders a route it has never opened while offline, which is the
   behaviour the shell precache used to provide. */
const APP_PRECACHE = {
  "dbd": [
    "/island/_astro/dbd.DMElnMne.css"
  ],
  "elden": [
    "/island/_astro/elden.CmDwNStp.css"
  ],
  "isaac": [
    "/island/_astro/isaac.Bi7e0JxZ.css"
  ],
  "poe2": [
    "/island/_astro/poe2.ClgEt_n8.css"
  ],
  "rust": [
    "/island/_astro/rust.ieei0MWZ.css"
  ],
  "terraria": [
    "/island/_astro/terraria.DkZhvNLA.css"
  ],
  "wardogs": [
    "/island/_astro/wardogs.3wckV64b.css"
  ]
};

/* Reverse map, so a runtime re-fetch of one of those stylesheets is written
   back to the app bucket instead of quietly re-growing the shell cache. */
const ROUTE_CSS = {
  "/island/_astro/dbd.DMElnMne.css": "dbd",
  "/island/_astro/elden.CmDwNStp.css": "elden",
  "/island/_astro/isaac.Bi7e0JxZ.css": "isaac",
  "/island/_astro/poe2.ClgEt_n8.css": "poe2",
  "/island/_astro/rust.ieei0MWZ.css": "rust",
  "/island/_astro/terraria.DkZhvNLA.css": "terraria",
  "/island/_astro/wardogs.3wckV64b.css": "wardogs"
};

const appCacheName = (slug) => 'fi-app-' + slug + '-' + (APP_VERS[slug] || '0');
const spriteCacheName = (slug) => 'fi-sprites-' + slug + '-' + (SPRITE_APPS[slug] ? SPRITE_APPS[slug].ver : '0');
const tileCacheName = (slug) => 'fi-tiles-' + slug + '-' + (TILE_APPS[slug] ? TILE_APPS[slug].ver : '0');

/** Root-absolute prefix of an app's sprite dir, or null if it has no tier. */
function spriteBase(slug) {
  const cfg = SPRITE_APPS[slug];
  return cfg ? BASE + '/apps/' + slug + '/' + cfg.dir + '/' : null;
}

/** Root-absolute prefix of an app's map-tile dir, or null if it has no tier. */
function tileBase(slug) {
  const cfg = TILE_APPS[slug];
  return cfg ? BASE + '/apps/' + slug + '/' + cfg.dir + '/' : null;
}

/** slug for a /island/apps/<slug>/... URL, else null. */
function appSlug(pathname) {
  const m = pathname.match(new RegExp('^' + BASE + '/apps/([^/]+)/'));
  return m ? m[1] : null;
}

self.addEventListener('install', (event) => {
  event.waitUntil(
    Promise.all([
      caches
        .open(SHELL_CACHE)
        // addAll is all-or-nothing; one 404 would leave the SW uninstalled forever.
        .then((c) => Promise.all(PRECACHE.map((u) => c.add(u).catch(() => {})))),
      // Same tolerance, per app bucket.
      ...Object.keys(APP_PRECACHE).map((slug) =>
        caches
          .open(appCacheName(slug))
          .then((c) => Promise.all(APP_PRECACHE[slug].map((u) => c.add(u).catch(() => {}))))
      ),
    ]).then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(
        keys.map((k) => {
          // Tier 1: stale shell buckets.
          if (k.startsWith('fi-shell-') && k !== SHELL_CACHE) return caches.delete(k);
          // Tier 2: stale per-app buckets - only for the app whose version moved.
          if (k.startsWith('fi-app-')) {
            const rest = k.slice('fi-app-'.length);
            const cut = rest.lastIndexOf('-');
            const slug = cut > 0 ? rest.slice(0, cut) : rest;
            if (!(slug in APP_VERS)) return caches.delete(k);
            if (k !== appCacheName(slug)) return caches.delete(k);
          }
          // Tier 2b: stale sprite buckets. Same test as tier 2, one bucket per
          // app that declares spriteWarm - so a data refresh (new contentHash)
          // drops the old sprite set and the app re-warms the new one against a
          // clean bucket, and a route that stops declaring spriteWarm has its
          // bucket reclaimed instead of leaking megabytes on every phone.
          if (k.startsWith('fi-sprites-')) {
            const rest = k.slice('fi-sprites-'.length);
            const cut = rest.lastIndexOf('-');
            const slug = cut > 0 ? rest.slice(0, cut) : rest;
            if (!(slug in SPRITE_APPS)) return caches.delete(k);
            if (k !== spriteCacheName(slug)) return caches.delete(k);
          }
          // Tier 2c: stale map-tile buckets. Identical test to tier 2b, one
          // bucket per app that declares tileWarm - so a regenerated pyramid
          // (new contentHash) drops the old tiles instead of leaving two
          // pyramids resident, and a route that stops declaring tileWarm has
          // its bucket reclaimed instead of stranding tens of MB on a phone.
          if (k.startsWith('fi-tiles-')) {
            const rest = k.slice('fi-tiles-'.length);
            const cut = rest.lastIndexOf('-');
            const slug = cut > 0 ? rest.slice(0, cut) : rest;
            if (!(slug in TILE_APPS)) return caches.delete(k);
            if (k !== tileCacheName(slug)) return caches.delete(k);
          }
          // fi-img-* is deliberately untouched: a shell deploy must never evict
          // a phone's downloaded item icons.
          return undefined;
        })
      )
    ).then(() => self.clients.claim())
  );
});

/** Cache-first + LRU. cache.keys() is insertion-ordered, so the head is oldest. */
async function cacheFirstLru(request) {
  const cache = await caches.open(IMAGE_CACHE);
  const hit = await cache.match(request);
  if (hit) return hit;
  const res = await fetch(request);
  if (res && res.ok) {
    await cache.put(request, res.clone());
    const keys = await cache.keys();
    if (keys.length > IMAGE_LRU_MAX) {
      const over = keys.length - IMAGE_LRU_MAX;
      for (let i = 0; i < over; i++) await cache.delete(keys[i]);
    }
  }
  return res;
}

/** Stale-while-revalidate: instant from cache, refreshed in the background. */
async function staleWhileRevalidate(request, cacheName) {
  const cache = await caches.open(cacheName);
  const hit = await cache.match(request);
  const network = fetch(request)
    .then((res) => {
      if (res && res.ok) cache.put(request, res.clone());
      return res;
    })
    .catch(() => null);
  return hit || (await network) || Response.error();
}

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;
  if (!url.pathname.startsWith(BASE + '/')) return;
  // Never intercept or cache sw.js itself: the settings page polls it with a
  // unique cache-busting query, and the catch-all would store every such URL
  // in SHELL_CACHE forever (verifier blocker 2026-08-31). Let the network own it.
  if (url.pathname === BASE + '/sw.js') return;

  // Navigations: network-first, fall back to the cached page, then /offline/.
  if (req.mode === 'navigate') {
    event.respondWith(
      fetch(req)
        .then((res) => {
          const copy = res.clone();
          caches.open(SHELL_CACHE).then((c) => c.put(req, copy));
          return res;
        })
        .catch(() => caches.match(req).then((hit) => hit || caches.match(OFFLINE_URL)))
    );
    return;
  }

  // config.js: network-first (auth/secrets sentinel - a precached copy would
  // pin stale secrets across a secrets-only redeploy). Cache the fresh copy for
  // an offline fallback only.
  if (url.pathname === BASE + '/config.js') {
    event.respondWith(
      fetch(req)
        .then((res) => {
          if (res && res.ok && res.type === 'basic') {
            const copy = res.clone();
            caches.open(SHELL_CACHE).then((c) => c.put(req, copy));
          }
          return res;
        })
        .catch(() => caches.match(req).then((hit) => hit || Response.error()))
    );
    return;
  }

  const slug = appSlug(url.pathname);

  // App data JSON: stale-while-revalidate into that app's own bucket.
  if (slug && /\/data\/.+\.json$/.test(url.pathname)) {
    event.respondWith(staleWhileRevalidate(req, appCacheName(slug)));
    return;
  }

  // Sprite tier, BEFORE the image LRU on purpose. Sprites are .png, so without
  // this branch they fall into fi-img-v1 and its 2,000-entry cap silently
  // evicts most of a 6,180-file set - the bug this tier exists to fix. Served
  // cache-first out of the app's own versioned sprite bucket, with no cap: a
  // warmed sprite must still be there after the user browses 2,000 other icons.
  const spriteDir = slug ? spriteBase(slug) : null;
  if (spriteDir && url.pathname.startsWith(spriteDir)) {
    event.respondWith(
      caches.open(spriteCacheName(slug)).then((cache) =>
        cache.match(req).then(
          (hit) =>
            hit ||
            fetch(req).then((res) => {
              if (res && res.ok && res.type === 'basic') cache.put(req, res.clone());
              return res;
            })
        )
      )
    );
    return;
  }

  // Map-tile tier, BEFORE the image LRU for the same reason as sprites and
  // more urgently. A pyramid is hundreds-to-thousands of tile images, so a
  // single map pan through fi-img-v1 would blow its 2,000-ENTRY cap and evict
  // every OTHER route's downloaded item icons off the phone. Cache-first out of
  // the app's own versioned tile bucket, no cap, stored on miss - LAZILY, as
  // tiles are viewed. There is no warm message and nothing pre-fetches the
  // pyramid; a phone only ever holds the tiles it has actually looked at.
  const tileDir = slug ? tileBase(slug) : null;
  if (tileDir && url.pathname.startsWith(tileDir)) {
    event.respondWith(
      caches.open(tileCacheName(slug)).then((cache) =>
        cache.match(req).then(
          (hit) =>
            hit ||
            fetch(req).then((res) => {
              if (res && res.ok && res.type === 'basic') cache.put(req, res.clone());
              return res;
            })
        )
      )
    );
    return;
  }

  // App images ONLY: cache-first with an LRU cap, in a version-independent
  // bucket. Shell chrome images (favicon, /icons/*.svg) have no slug and fall
  // through to the shell cache-first branch below, where they hit the precache
  // instead of being re-fetched into - and counted against - the image LRU.
  if (slug && /\.(webp|png|jpe?g|gif|svg|avif)$/i.test(url.pathname)) {
    event.respondWith(cacheFirstLru(req));
    return;
  }

  // App code/CSS + shell chunks: cache-first, they are content-addressed.
  // caches.match() with no cacheName searches EVERY bucket, so a route
  // stylesheet precached into fi-app-<slug>-<ver> is found here unchanged.
  event.respondWith(
    caches.match(req).then(
      (hit) =>
        hit ||
        fetch(req).then((res) => {
          if (res && res.ok && res.type === 'basic') {
            const owner = ROUTE_CSS[url.pathname];
            const bucket = owner ? appCacheName(owner) : slug ? appCacheName(slug) : SHELL_CACHE;
            const copy = res.clone();
            caches.open(bucket).then((c) => c.put(req, copy));
          }
          return res;
        })
    )
  );
});

/**
 * Warm one sprite tier into the app's sprite bucket.
 *
 * The APP chooses the files (only it knows the current mode, and it already has
 * the 8.7 MB items.json parsed - re-deriving the list in here would double boot
 * cost on exactly the device this protects) and posts BARE FILENAMES; the SW
 * owns the caching and resolves them against the app's sprite dir.
 *
 * Per-tier COMPLETION MARKERS are stored as synthetic entries in the same
 * bucket, keyed to the dataset stamp the app posts. That means:
 *   - a finished tier is skipped on every later message (no re-fetch storm when
 *     the user flips modes back and forth),
 *   - a dataset refresh changes the stamp, so the tier re-warms,
 *   - a PARTIAL warm (the user went offline mid-way) writes no marker and is
 *     retried next time,
 *   - and a new contentHash mints a new bucket, so the markers vanish with the
 *     sprites they describe - the marker can never outlive its own cache.
 * No IndexedDB, no second state store: the cache IS the state.
 */
async function warmSpriteTiers(slug, data) {
  const base = spriteBase(slug);
  if (!base) return;
  const cache = await caches.open(spriteCacheName(slug));
  const stamp = String(data.stamp || '');

  // TWO accepted message shapes, one code path below.
  //
  // GENERIC (preferred, and what every new route posts):
  //   { tiers: [[name, files[]], ...], wantTiers: [name, ...] }
  // wantTiers is an OPTIONAL filter - when it is absent every listed tier is
  // warmed, so a single-tier route posts nothing but `tiers`. Tier names are
  // the app's own vocabulary ('base'/'sote' for Elden Ring, 'vanilla'/'calamity'
  // for Terraria); this worker only uses them as marker keys, so nothing here
  // has to know a mod's name ever again.
  //
  // LEGACY (Terraria, still shipping): { vanilla, calamity, wantCalamity }.
  // It is kept as an exact behavioural alias - vanilla always, calamity only
  // while the mod is on - so the mod flip still re-posts and warms tier 2 then,
  // and the marker keys ('vanilla'/'calamity') are unchanged, which matters:
  // a changed key would re-warm ~4 MB on every Terraria phone for nothing.
  let tiers;
  if (Array.isArray(data.tiers)) {
    const want = Array.isArray(data.wantTiers) ? data.wantTiers : null;
    tiers = data.tiers.filter(
      (t) => Array.isArray(t) && t.length >= 2 && (!want || want.indexOf(t[0]) !== -1)
    );
  } else {
    tiers = [['vanilla', data.vanilla]];
    // The second tier is only worth its bytes while the mod is actually on;
    // flipping Calamity on re-posts the message and warms it then.
    if (data.wantCalamity) tiers.push(['calamity', data.calamity]);
  }

  for (const [tier, files] of tiers) {
    if (!Array.isArray(files) || !files.length) continue;
    const marker = new Request(BASE + '/__warm/' + slug + '/' + tier + '/' + encodeURIComponent(stamp));
    if (await cache.match(marker)) continue;

    let complete = true;
    // Batched: a single Promise.all over 6,180 requests would open the floodgates
    // on a phone. 24 at a time keeps the warm in the background where it belongs.
    for (let i = 0; i < files.length; i += 24) {
      const batch = files.slice(i, i + 24);
      const done = await Promise.all(
        batch.map((f) => {
          const url = base + f;
          // Already resident (e.g. fetched on demand while browsing) - never
          // re-download it just to mark the tier complete. Three-way on purpose:
          // the abort cap below has to tell "already had it" from "just got it"
          // from "failed", which a boolean cannot.
          return cache.match(url).then((hit) =>
            hit ? 'hit' : cache.add(url).then(() => 'fetched', () => 'fail')
          );
        })
      );
      if (done.some((r) => r === 'fail')) complete = false;
      // FIRST-BATCH ABORT CAP. If the opening batch produced no successes and
      // no already-cached hits, the whole sweep is doomed - a wrong path, a
      // renamed sprite dir, an offline device - and every remaining request
      // will fail the same way. cache.add() rejections are swallowed by the
      // ()=>'fail' handler, so without this the worker grinds through all
      // ~6,200 doomed requests on EVERY page load and nothing surfaces.
      // Bail after ~24 instead. No marker is written, so a later load with a
      // working path still warms normally - this caps the damage, it does not
      // give up permanently.
      if (i === 0 && !done.some((r) => r === 'fetched' || r === 'hit')) return;
    }
    if (complete) await cache.put(marker, new Response('1'));
  }
}

self.addEventListener('message', (event) => {
  const data = event.data || {};

  /** Per-route "make available offline" warm button (P1 UI, protocol here now). */
  if (data.type === 'fi-warm' && data.urls) {
    const bucket = data.slug ? appCacheName(data.slug) : SHELL_CACHE;
    event.waitUntil(
      caches.open(bucket).then((c) => Promise.all(data.urls.map((u) => c.add(u).catch(() => {}))))
    );
    return;
  }

  // Tiered sprite warm. The slug comes from the POSTING CLIENT's URL, not the
  // message body: a page can only ever warm its own route's sprite bucket, and
  // SPRITE_APPS gates it so an unknown slug is simply ignored.
  if (data.type === 'warm-sprites') {
    let slug = null;
    try {
      const m = new URL(event.source.url).pathname.match(new RegExp('^' + BASE + '/([^/]+)/'));
      slug = m ? m[1] : null;
    } catch (e) {
      slug = null;
    }
    if (slug && SPRITE_APPS[slug]) event.waitUntil(warmSpriteTiers(slug, data));
  }
});
