/* WARDOGS Companion - vanilla JS, no build step, no modules.
 *
 * Data: data/meta.json + one JSON per entity group, all generated by
 * tools/build_data.mjs. THIS FILE HAND-WRITES NO GAME PROSE. Every sentence a
 * user reads about an entity comes out of `beginner.{whatItIs,whyItMatters,
 * whenToUseIt}` in the data, which the pipeline merges forward from
 * tools/beginner-notes/. Chrome labels ("Weapons", "Your first 10 minutes") are
 * UI, not game facts.
 *
 * PORT NOTES (fiiiish-app shell):
 *  - The shell strips #topbar and #siteFoot. Every lookup into either is
 *    null-guarded, so a stripped id is a no-op, not a crash.
 *  - This app owns location.hash -> the registry entry must set
 *    nativeHashRouting: true. The shared shim fires synchronously and would
 *    lose the race against the data fetch.
 *  - No service worker is registered here. The shell owns exactly one. The
 *    block at the bottom of this file only WAITS for whichever worker already
 *    controls the page and posts it the sprite-warm list - that is the app
 *    half of registry.spriteWarm and it must not be removed. Standalone, with
 *    no worker, it no-ops.
 *  - No absolute deploy URL anywhere. All app assets are '/island/apps/wardogs/'-relative so the
 *    assembler's rewrite lands them under /island/apps/wardogs/.
 */
'use strict';

/* ------------------------------------------------------------------ state */

const S = {
  meta: null,
  groups: {},        // key -> [entities]
  gmeta: [],         // ordered group descriptors (from meta.wiki)
  gmap: {},          // key -> descriptor
  byId: {},          // "group:id" -> entity
  byName: {},        // lowercased display name -> "group:id"
  index: [],         // search index rows
  view: 'start',
  q: '',
  wCat: 'all',       // weapons tab category filter
  iGroup: 'all',     // items tab group filter
  iCat: 'all',       // items tab category filter
  onlyUnlockable: false,
  booted: false
};

const $ = sel => document.querySelector(sel);
const app = () => $('#app');
const esc = s => String(s == null ? '' : s).replace(/[&<>"']/g, c => ({
  '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;'
}[c]));

/* Which of the five tabs each entity group lives on. A group the pipeline adds
   later and this map has not heard of lands on More rather than vanishing. */
const TAB_OF = {
  weapons: 'weapons',
  attachments: 'items', gear: 'items', ammo: 'items', 'ammo-types': 'items',
  specializations: 'items', medical: 'items', tactical: 'items',
  deployables: 'items', vehicles: 'items',
  factions: 'more', maps: 'more', 'game-modes': 'more', classes: 'more',
  mechanics: 'more', glossary: 'more',
  builds: 'builds'
};
const ITEM_ORDER = ['gear', 'attachments', 'ammo', 'ammo-types', 'specializations',
  'medical', 'tactical', 'deployables', 'vehicles'];
const MORE_ORDER = ['game-modes', 'mechanics', 'maps', 'factions', 'classes', 'glossary'];

/* The Start walkthrough is an ORDERED SELECTION of existing entities, not new
   prose. Anything that does not resolve is dropped, so a pipeline rename
   shortens the list instead of rendering a dead step. */
const START_STEPS = [
  'game-modes:control-zone',
  'mechanics:squads',
  'mechanics:respawning-and-hq',
  'mechanics:winning-a-match',
  'mechanics:hot-zone',
  'mechanics:money',
  'mechanics:death-penalties',
  'mechanics:wardog-level-and-unlocks',
  'mechanics:how-ammo-works',
  'mechanics:medical-and-revives'
];

/* ------------------------------------------------------- persistence layer */

/* ONE namespaced key holding the whole blob. The name deliberately contains no
   "token", "auth" or "secret" and does not start with "sb-": import.astro's
   CREDENTIAL regex is tested BEFORE its allowlist and would silently drop this
   key from every backup and restore (R11 - do not relax the regex, rename the
   key). Multi-profile from day one; retrofitting profiles orphans saved data. */
const LS_KEY = 'wardogs_companion_v1'; // gitleaks:allow - localStorage namespace, not a secret

let ST = null;          // the whole blob
let saveTimer = null;

function blankProfile(name) {
  return { name: name || 'Loadout 1', manual: {}, imported: {}, pins: [], synced_at: null };
}
function blankState() {
  return { v: 1, active: 'p1', profiles: { p1: blankProfile('Loadout 1') } };
}

function loadState() {
  try {
    const raw = localStorage.getItem(LS_KEY);
    if (!raw) return blankState();
    const o = JSON.parse(raw);
    if (!o || typeof o !== 'object' || !o.profiles || typeof o.profiles !== 'object') return blankState();
    for (const id of Object.keys(o.profiles)) {
      const p = o.profiles[id];
      if (!p || typeof p !== 'object') { delete o.profiles[id]; continue; }
      if (typeof p.name !== 'string') p.name = 'Loadout';
      if (!p.manual || typeof p.manual !== 'object') p.manual = {};
      if (!p.imported || typeof p.imported !== 'object') p.imported = {};
      if (!Array.isArray(p.pins)) p.pins = [];
    }
    if (!Object.keys(o.profiles).length) return blankState();
    if (!o.profiles[o.active]) o.active = Object.keys(o.profiles)[0];
    o.v = 1;
    return o;
  } catch (e) {
    return blankState();
  }
}

function showSave(kind) {
  const el = $('#savePill');
  if (!el) return;
  el.hidden = false;
  el.className = 'save-pill' + (kind === 'saved' ? ' ok' : kind === 'failed' ? ' bad' : '');
  el.textContent = kind === 'saving' ? 'saving...' : kind === 'saved' ? 'saved' : 'save failed';
  if (kind === 'saved') {
    setTimeout(function () { const e2 = $('#savePill'); if (e2 && e2.textContent === 'saved') e2.hidden = true; }, 1400);
  }
}

/* 300 ms debounced write behind a visible pill. Never write synchronously per
   click - a fast tapper would hit localStorage on every keystroke. */
function saveState() {
  showSave('saving');
  if (saveTimer) clearTimeout(saveTimer);
  saveTimer = setTimeout(function () {
    saveTimer = null;
    try {
      localStorage.setItem(LS_KEY, JSON.stringify(ST));
      showSave('saved');
    } catch (e) {
      showSave('failed');
    }
  }, 300);
}

function prof() {
  if (!ST) ST = blankState();
  if (!ST.profiles[ST.active]) ST.active = Object.keys(ST.profiles)[0];
  return ST.profiles[ST.active];
}

/* Sparse manual-override layer over imported data. A read falls through
   manual -> imported; a write whose value EQUALS the imported value deletes the
   manual key, so the override layer only ever holds real divergence and a
   future import is not fought by stale ticks. */
function impGet(p, group, key) {
  const g = p.imported && p.imported[group];
  return g ? g[key] : undefined;
}
function ovGet(p, group, key, dflt) {
  const m = p.manual && p.manual[group];
  if (m && Object.prototype.hasOwnProperty.call(m, key)) return m[key];
  const iv = impGet(p, group, key);
  return iv === undefined ? dflt : iv;
}
function ovSet(group, key, val) {
  const p = prof();
  const iv = impGet(p, group, key);
  if (!p.manual) p.manual = {};
  if (val === iv || (iv === undefined && (val === false || val === null))) {
    if (p.manual[group]) {
      delete p.manual[group][key];
      if (!Object.keys(p.manual[group]).length) delete p.manual[group];
    }
  } else {
    if (!p.manual[group]) p.manual[group] = {};
    p.manual[group][key] = val;
  }
  saveState();
}

function myLevel() {
  const v = ovGet(prof(), 'meta', 'level', 1);
  const n = parseInt(v, 10);
  return isFinite(n) && n > 0 ? n : 1;
}
function setMyLevel(n) { ovSet('meta', 'level', n); }
function isOwned(k) { return ovGet(prof(), 'owned', k, false) === true; }
function toggleOwned(k) { ovSet('owned', k, !isOwned(k)); }
function isPinned(k) { const p = prof(); return p.pins.indexOf(k) !== -1; }
function togglePin(k) {
  const p = prof();
  const i = p.pins.indexOf(k);
  if (i >= 0) p.pins.splice(i, 1); else p.pins.push(k);
  saveState();
  return i < 0;
}

/* ------------------------------------------------------------- formatting */

const LABELS = {
  caliber: 'Caliber', fireMode: 'Fire mode', weightKg: 'Weight', price: 'Price',
  acceptsAttachments: 'Takes attachments', magazines: 'Magazines',
  wardogLevel: 'Unlocks at', unlockPrice: 'Unlock cost', rounds: 'Rounds',
  weapons: 'Fits', weaponGroup: 'Fits group', zoom: 'Zoom', zeroing: 'Zeroing',
  adsTrade: 'Aim speed', damageReduction: 'Damage reduction', protects: 'Protects',
  quickslots: 'Quick slots', reloadSpeed: 'Reload speed',
  equipHolsterSpeed: 'Equip / holster speed', grid: 'Grid', slots: 'Slots',
  slingSlots: 'Sling slots', subcategory: 'Type', seats: 'Seats', armor: 'Armor',
  logisticsCrates: 'Carries logistics crates', standingSpace: 'Standing space',
  weaponMount: 'Weapon mount', maxSpeedKmh: 'Top speed', fuelCapacityL: 'Fuel capacity',
  fuelEconomyLPerKm: 'Fuel use', crew: 'Crew', armament: 'Armament',
  xpCategory: 'XP track', countermeasures: 'Countermeasures', ammoTypes: 'Ammo types',
  hpUnlockLevel: 'HP unlocks at', hpUnlockPrice: 'HP unlock cost',
  apUnlockLevel: 'AP unlocks at', apUnlockPrice: 'AP unlock cost',
  baseDamage: 'Base damage', standardPerRound: 'Standard round',
  standardPerBox: 'Standard box', usedBy: 'Used by', inGameName: 'Called in game',
  slotType: 'Slot', payload: 'Payload', launchTube: 'Launch tube', focus: 'Focus',
  unlocks: 'Unlocks', archetype: 'Archetype', teamColour: 'Team colour',
  size: 'Map size', controlZoneDiameter: 'Control Zone diameter',
  controlZonePlacement: 'Control Zone placement', pointsOfInterest: 'Points of interest',
  factions: 'Factions', playersPerFaction: 'Players per faction',
  playersPerMatch: 'Players per match', pointsPerCycle: 'Points per tick',
  cycleSeconds: 'Tick length', pointsToWin: 'Points to win'
};

/* Keys never shown as a stat row: identity, plumbing, or rendered elsewhere. */
const SKIP = ['id', 'name', 'term', 'category', 'sourceSection', 'sourcePage', 'summary',
  'sourceUrl', 'beginner', 'icon', 'iconIsPlaceholder', 'iconPlaceholderReason',
  'dataCompleteness', 'relatedLabel', 'related', 'tags', 'colourHex', 'seeAlso'];

/* Fields rendered as tappable links instead of text. */
const LINK_FIELDS = ['caliber', 'magazines', 'weapons', 'usedBy', 'ammoTypes', 'unlocks'];

function money(n) {
  if (n === 0) return 'Free';
  if (typeof n !== 'number') return String(n);
  return '$' + n.toLocaleString('en-US');
}
function fmtVal(key, v) {
  if (v === null || v === undefined || v === '') return '';
  if (typeof v === 'boolean') return v ? 'Yes' : 'No';
  if (Array.isArray(v)) return v.map(function (x) { return typeof x === 'object' && x ? (x.name || '') : String(x); }).filter(Boolean).join(', ');
  if (key === 'price' || key === 'unlockPrice' || key === 'hpUnlockPrice' || key === 'apUnlockPrice' || key === 'standardPerRound' || key === 'standardPerBox') return money(v);
  if (key === 'weightKg') return v + ' kg';
  if (key === 'maxSpeedKmh') return v + ' km/h';
  if (key === 'fuelCapacityL') return v + ' L';
  if (key === 'fuelEconomyLPerKm') return v + ' L/km';
  /* TWO KINDS OF GATE, and the source stores them in one field. A NUMBER is the
     account-wide WARDOG level; a STRING is a per-class XP gate the source
     already spells out ("Assault Lvl 10"). Printing "WARDOG level Assault Lvl
     10" would invent a requirement, so the string is passed through untouched. */
  if (key === 'wardogLevel' || key === 'hpUnlockLevel' || key === 'apUnlockLevel') {
    return typeof v === 'number' ? 'WARDOG level ' + v : String(v);
  }
  if (key === 'cycleSeconds') return v + ' seconds';
  return String(v);
}
function labelOf(key) {
  if (LABELS[key]) return LABELS[key];
  return key.replace(/([A-Z])/g, ' $1').replace(/^./, function (c) { return c.toUpperCase(); });
}
/* Split on sentence ends WITHOUT a lookbehind - Safari only shipped lookbehind
   in 16.4 and a regex the parser rejects takes the whole file down. */
function firstSentences(text, n) {
  if (!text) return '';
  const s = String(text);
  const want = n || 1;
  let out = '', count = 0, i = 0;
  while (i < s.length) {
    out += s[i];
    if ('.!?'.indexOf(s[i]) !== -1 && (i + 1 >= s.length || /\s/.test(s[i + 1]))) {
      count++;
      if (count >= want) break;
    }
    i++;
  }
  return out.trim();
}

/* --------------------------------------------------------------- entities */

function nameOf(e, gk) {
  const d = S.gmap[gk];
  const nf = (d && d.nameField) || 'name';
  return e[nf] || e.name || e.term || e.id;
}
function keyOf(gk, id) { return gk + ':' + id; }
function ent(k) { return S.byId[k] || null; }
function groupTitle(gk) { const d = S.gmap[gk]; return (d && d.title) || gk; }

function resolveName(name) {
  if (!name) return null;
  return S.byName[String(name).toLowerCase().trim()] || null;
}

function iconHtml(e, gk, size) {
  const cls = 'spr s' + (size || 44);
  const ph = e.iconIsPlaceholder ? ' ph' : '';
  if (!e.icon) return '<span class="spr-wrap miss' + ph + '"><span class="' + cls + '"></span></span>';
  return '<span class="spr-wrap' + ph + '"><img class="' + cls + '" src="' + esc(e.icon) +
    '" alt="" loading="lazy" onerror="wdSprErr(this)" /></span>';
}
window.wdSprErr = function (img) {
  img.style.visibility = 'hidden';
  const w = img.closest('.spr-wrap');
  if (w) w.classList.add('miss');
};

/* The two chips every list row shows: what it costs and what it needs. */
function costChips(e) {
  const out = [];
  if (typeof e.price === 'number') {
    out.push(e.price === 0
      ? '<span class="chip free">Free</span>'
      : '<span class="chip cost">' + esc(money(e.price)) + '</span>');
  }
  if (e.wardogLevel) {
    out.push('<span class="chip lvl">' +
      (typeof e.wardogLevel === 'number' ? 'Lv ' + esc(e.wardogLevel) : esc(e.wardogLevel)) +
      '</span>');
  }
  return out.join('');
}

function beginnerHtml(e) {
  const b = e.beginner;
  if (!b || (!b.whatItIs && !b.whyItMatters && !b.whenToUseIt)) {
    return '<div class="beg-missing">Plain-language notes for this entry have not been written yet. ' +
      'The stats below come straight from the pull; the "what it is / why it matters / when to use it" ' +
      'lines are still owed for this group.</div>';
  }
  let h = '<div class="beg">';
  const rows = [['What it is', b.whatItIs], ['Why it matters', b.whyItMatters], ['When to use it', b.whenToUseIt]];
  for (const r of rows) {
    if (!r[1]) continue;
    h += '<p class="bh">' + esc(r[0]) + '</p><p class="bp">' + esc(r[1]) + '</p>';
  }
  h += '</div>';
  return h;
}

function linkChip(k, label) {
  if (!k) return '<span class="chip">' + esc(label) + '</span>';
  return '<button class="lchip" data-ent="' + esc(k) + '">' + esc(label) + '</button>';
}

function linkFieldHtml(key, v) {
  const vals = Array.isArray(v) ? v : [v];
  const chips = vals.map(function (item) {
    if (item && typeof item === 'object') {
      const k = item.id ? findByIdAnywhere(item.id) : resolveName(item.name);
      const lab = item.name + (item.level ? ' (Lv ' + item.level + ')' : '');
      return linkChip(k, lab);
    }
    return linkChip(resolveName(item), String(item));
  }).join('');
  return '<div class="linkrow">' + chips + '</div>';
}

function findByIdAnywhere(id) {
  for (const d of S.gmeta) {
    if (S.byId[keyOf(d.key, id)]) return keyOf(d.key, id);
  }
  return null;
}

function statsHtml(e, gk) {
  let rows = '';
  for (const key of Object.keys(e)) {
    if (SKIP.indexOf(key) !== -1) continue;
    const v = e[key];
    if (v === null || v === undefined || v === '') continue;
    if (Array.isArray(v) && !v.length) continue;
    const lab = labelOf(key);
    if (LINK_FIELDS.indexOf(key) !== -1) {
      rows += '<div class="st"><span class="k">' + esc(lab) + '</span><span class="v">' + linkFieldHtml(key, v) + '</span></div>';
    } else {
      const txt = fmtVal(key, v);
      if (!txt) continue;
      rows += '<div class="st"><span class="k">' + esc(lab) + '</span><span class="v">' + esc(txt) + '</span></div>';
    }
  }
  if (!rows) return '';
  return '<div class="sec-h">Stats as pulled</div><div class="stats">' + rows + '</div>';
}

/* ------------------------------------------------------------ detail sheet */

let sheetOpen = false;

function openEntity(k) {
  const e = ent(k);
  if (!e) return;
  const gk = k.slice(0, k.indexOf(':'));
  const nm = nameOf(e, gk);
  const body = $('#sheetBody');
  const sh = $('#sheet');
  if (!body || !sh) return;

  let h = '<button class="sheet-close" data-close>Close</button><div class="sheet-grab"></div>';
  h += '<div class="sheet-hero">' + iconHtml(e, gk, 88) + '<div style="min-width:0">';
  h += '<h3>' + esc(nm) + '</h3>';
  h += '<div class="ssub">' + esc(groupTitle(gk)) + (e.category ? ' &middot; ' + esc(e.category) : '') + '</div>';
  const chips = costChips(e);
  if (chips) h += '<div class="row wrap g6">' + chips + '</div>';
  h += '</div></div>';

  if (e.iconIsPlaceholder) {
    const why = e.iconPlaceholderReason === 'source-image-404'
      ? 'The source links an image here that its own server returns 404 for, so this is a stand-in drawn locally.'
      : 'The source publishes no image for this kind of entry, so this is a stand-in drawn locally.';
    h += '<div class="ph-note">' + esc(why) + '</div>';
  }
  if (e.dataCompleteness === 'name-only') {
    h += '<div class="ph-note">The source publishes little more than the name for this entry. What is below is all there is until the Early Access pull.</div>';
  }

  h += beginnerHtml(e);

  if (Array.isArray(e.tags) && e.tags.length) {
    h += '<div class="row wrap g6 mt8">' + e.tags.map(function (t) {
      return '<span class="chip">' + esc(t) + '</span>';
    }).join('') + '</div>';
  }

  h += statsHtml(e, gk);

  // Cross-links the stat table does not cover.
  const rel = [];
  if (Array.isArray(e.related)) {
    for (const r of e.related) {
      if (S.gmap[r]) rel.push('<button class="lchip" data-group="' + esc(r) + '">' + esc(groupTitle(r)) + '</button>');
      else { const rk = resolveName(r); if (rk) rel.push(linkChip(rk, nameOf(ent(rk), rk.slice(0, rk.indexOf(':'))))); }
    }
  }
  if (Array.isArray(e.seeAlso)) {
    for (const r of e.seeAlso) {
      const rk = resolveName(r);
      rel.push(linkChip(rk, r));
    }
  }
  if (gk === 'weapons' && e.acceptsAttachments) {
    const fits = attachmentsFor(e);
    if (fits.length) {
      rel.push('<button class="lchip" data-fits="' + esc(e.id) + '">' + fits.length +
        (fits.length === 1 ? ' attachment lists' : ' attachments list') + ' this weapon</button>');
    }
  }
  if (rel.length) h += '<div class="sec-h">Related</div><div class="linkrow">' + rel.join('') + '</div>';

  // Tracker actions.
  h += '<div class="actrow">';
  h += '<button class="tbtn' + (isPinned(k) ? ' on' : '') + '" data-pin="' + esc(k) + '">' + (isPinned(k) ? 'Pinned' : 'Pin') + '</button>';
  if (e.wardogLevel || e.unlockPrice) {
    h += '<button class="tbtn' + (isOwned(k) ? ' on' : '') + '" data-own="' + esc(k) + '">' + (isOwned(k) ? 'Unlocked' : 'Mark unlocked') + '</button>';
  }
  h += '</div>';

  if (e.sourceUrl) {
    h += '<div class="sec-h">Source</div><p class="srcbox">Facts on this page were read from <a href="' +
      esc(e.sourceUrl) + '" target="_blank" rel="noopener noreferrer">' + esc(e.sourceUrl) + '</a>. ' +
      esc(S.meta && S.meta.disclaimer ? S.meta.disclaimer : 'Pre-release data.') + '</p>';
  }

  body.innerHTML = h;
  body.scrollTop = 0;
  sh.hidden = false;
  sheetOpen = true;
  try { document.body.style.overflow = 'hidden'; } catch (err) { /* no-op */ }
  setHash('#/e/' + k.replace(':', '/'));
}

function closeSheet() {
  const sh = $('#sheet');
  if (sh) sh.hidden = true;
  sheetOpen = false;
  try { document.body.style.overflow = ''; } catch (err) { /* no-op */ }
  setHash('#/' + S.view);
}

/* Compatibility is only ever what the SOURCE stated: an attachment's own
   `weapons` list, or a `weaponGroup` that is exactly this weapon's name. No
   caliber-based guessing - inferring a fit the source never claimed would put a
   number on screen that the vault wiki does not carry. */
function attachmentsFor(w) {
  const list = S.groups.attachments || [];
  const wname = String(w.name || '').toLowerCase();
  return list.filter(function (a) {
    if (Array.isArray(a.weapons) && a.weapons.some(function (x) { return String(x).toLowerCase() === wname; })) return true;
    if (a.weaponGroup && String(a.weaponGroup).toLowerCase() === wname) return true;
    return false;
  });
}

/* ------------------------------------------------------------------ search */

function buildIndex() {
  S.index = [];
  for (const d of S.gmeta) {
    const list = S.groups[d.key] || [];
    for (const e of list) {
      const nm = nameOf(e, d.key);
      const hay = (nm + ' ' + (e.category || '') + ' ' + (e.summary || '') + ' ' + (e.caliber || '')).toLowerCase();
      S.index.push({ k: keyOf(d.key, e.id), g: d.key, n: nm, hay: hay });
    }
  }
}

function searchRows(q, excludeTabs) {
  const s = q.toLowerCase().trim();
  if (!s) return [];
  const out = [];
  for (const r of S.index) {
    if (excludeTabs && excludeTabs.indexOf(TAB_OF[r.g] || 'more') !== -1) continue;
    if (r.hay.indexOf(s) === -1) continue;
    out.push(r);
    if (out.length >= 30) break;
  }
  out.sort(function (a, b) {
    const as = a.n.toLowerCase().indexOf(s), bs = b.n.toLowerCase().indexOf(s);
    const ar = as === 0 ? 0 : as > 0 ? 1 : 2, br = bs === 0 ? 0 : bs > 0 ? 1 : 2;
    return ar - br || a.n.localeCompare(b.n);
  });
  return out;
}

function searchHtml(placeholder) {
  return '<div class="search-wrap">' +
    '<span class="search-ic">&#128269;</span>' +
    '<input id="q" class="search" type="search" autocomplete="off" autocorrect="off" ' +
    'spellcheck="false" placeholder="' + esc(placeholder) + '" value="' + esc(S.q) + '" />' +
    (S.q ? '<button class="search-clear" data-clearq aria-label="Clear search">&#10005;</button>' : '') +
    '<div id="suggest"></div></div>';
}

/* The dropdown carries every entity the CURRENT tab cannot show, so the search
   field genuinely reaches all 219 entries from all five tabs. */
function renderSuggest() {
  const box = $('#suggest');
  if (!box) return;
  if (!S.q.trim()) { box.innerHTML = ''; box.className = ''; return; }
  const exclude = (S.view === 'weapons' || S.view === 'items') ? [S.view] : [];
  const rows = searchRows(S.q, exclude);
  if (!rows.length) {
    if (exclude.length) { box.innerHTML = ''; box.className = ''; return; }
    box.className = 'suggest';
    box.innerHTML = '<div class="sug-empty">Nothing matches "' + esc(S.q) + '".</div>';
    return;
  }
  box.className = 'suggest';
  box.innerHTML = rows.map(function (r) {
    return '<button class="sug-row" data-ent="' + esc(r.k) + '">' +
      '<span class="nm">' + esc(r.n) + '</span>' +
      '<span class="tg">' + esc(groupTitle(r.g)) + '</span></button>';
  }).join('');
}

/* -------------------------------------------------------------- views: Start */

function renderStart() {
  let h = '<div class="view">';
  h += searchHtml('Search everything in WARDOGS');

  h += '<h2 class="vh">Your first 10 minutes</h2>';
  h += '<p class="small muted" style="margin:-4px 2px 12px">Read these ten in order and you know how a WARDOGS match works. Tap any step for the full explanation.</p>';
  h += '<ol class="steps">';
  let steps = 0;
  for (const k of START_STEPS) {
    const e = ent(k);
    if (!e) continue;
    steps++;
    const gk = k.slice(0, k.indexOf(':'));
    const b = e.beginner || {};
    const line = firstSentences(b.whatItIs, 2) || e.summary || '';
    h += '<li><button class="sl" style="display:block;background:none;border:0;padding:0;text-align:left;color:inherit;font-family:inherit;font-size:14px;font-weight:600" data-ent="' + esc(k) + '">' + esc(nameOf(e, gk)) + '</button>' +
      '<div class="sd">' + esc(line) + ' <button class="more" style="background:none;border:0;padding:0;font:inherit;color:var(--accent-hi)" data-ent="' + esc(k) + '">More</button></div></li>';
  }
  h += '</ol>';
  if (!steps) h += '<div class="card">The walkthrough steps are not in this dataset. Use the Mechanics list on the More tab.</div>';

  /* Pick your first weapon: DERIVED, not curated. A weapon qualifies when the
     source published a price and no WARDOG level gate, which is exactly the set
     a brand-new account can walk in and buy; cheapest first, four of them. If a
     later pull adds a level to one of these it drops out on its own. */
  const cheap = (S.groups.weapons || []).slice().filter(function (w) {
    return typeof w.price === 'number' && !w.wardogLevel;
  }).sort(function (a, b) { return a.price - b.price; }).slice(0, 4);
  if (cheap.length) {
    h += '<h2 class="vh">Pick your first weapon</h2>';
    h += '<p class="small muted" style="margin:-4px 2px 12px">The cheapest weapons with no WARDOG level gate on them, so a new account can buy any of these today and a bad run costs the least.</p>';
    for (const w of cheap) {
      const b = w.beginner || {};
      h += '<button class="rowcard" data-ent="' + esc(keyOf('weapons', w.id)) + '">' +
        iconHtml(w, 'weapons', 44) +
        '<span class="rb"><span class="rn">' + esc(w.name) + '</span>' +
        '<span class="rm">' + esc(firstSentences(b.whyItMatters, 2) || w.summary || '') + '</span></span>' +
        '<span class="rc">' + costChips(w) + '</span></button>';
    }
  }

  // Glossary preview.
  const gl = S.groups.glossary || [];
  if (gl.length) {
    h += '<h2 class="vh">Words you will hear</h2>';
    h += '<p class="small muted" style="margin:-4px 2px 12px">' + gl.length + ' terms in plain English. Search above for any of them, or open the full list on More.</p>';
    h += '<div class="row wrap g6">' + gl.slice(0, 14).map(function (t) {
      return '<button class="lchip" data-ent="' + esc(keyOf('glossary', t.id)) + '">' + esc(t.term) + '</button>';
    }).join('') + '</div>';
    h += '<div class="row g8 mt8"><button class="tbtn" data-goto="more">Open the full glossary</button></div>';
  }

  h += rosterGapCardHtml();
  h += freshBlockHtml();
  h += '</div>';
  return h;
}

/* ------------------------------------------------------------ views: Weapons */

function renderWeapons() {
  const cats = ['all'].concat(distinct(S.groups.weapons || [], 'category'));
  let h = '<div class="view">';
  h += searchHtml('Search weapons and everything else');
  h += '<div class="chiprow">' + cats.map(function (c) {
    return '<button class="fbtn' + (S.wCat === c ? ' on' : '') + '" data-wcat="' + esc(c) + '">' +
      esc(c === 'all' ? 'All ' + (S.groups.weapons || []).length : c) + '</button>';
  }).join('') + '</div>';
  /* Directly under the "All 30" chip, because that chip is where a beginner
     forms the belief that 30 is the roster. */
  h += rosterGapNoteHtml(['weapons']);
  h += '<div class="row g8" style="margin-bottom:10px">' +
    '<button class="tbtn' + (S.onlyUnlockable ? ' on' : '') + '" data-unlockable>Hide what my WARDOG level ' + myLevel() + ' cannot buy</button></div>';
  h += '<div id="listRegion"></div>';
  h += '</div>';
  return h;
}

function weaponList() {
  const q = S.q.toLowerCase().trim();
  return (S.groups.weapons || []).filter(function (w) {
    if (S.wCat !== 'all' && w.category !== S.wCat) return false;
    if (S.onlyUnlockable && gatedAbove(w, myLevel())) return false;
    if (!q) return true;
    return (w.name + ' ' + (w.category || '') + ' ' + (w.caliber || '') + ' ' + (w.summary || '')).toLowerCase().indexOf(q) !== -1;
  });
}

function fillWeapons() {
  const box = $('#listRegion');
  if (!box) return;
  const list = weaponList();
  if (!list.length) {
    box.innerHTML = '<div class="card muted">No weapon matches that. The dropdown above searches every other tab.</div>';
    return;
  }
  box.innerHTML = '<div class="grid">' + list.map(function (w) {
    return '<button class="gcard" data-ent="' + esc(keyOf('weapons', w.id)) + '">' +
      '<span class="gi">' + iconHtml(w, 'weapons', 64) + '</span>' +
      '<span class="gn">' + esc(w.name) + '</span>' +
      '<span class="gm">' + esc(w.category || '') + (w.caliber ? ' &middot; ' + esc(w.caliber) : '') + '</span>' +
      '<span class="gc">' + costChips(w) + '</span></button>';
  }).join('') + '</div>';
}

/* -------------------------------------------------------------- views: Items */

function itemGroups() {
  return ITEM_ORDER.filter(function (g) { return (S.groups[g] || []).length; })
    .concat(S.gmeta.filter(function (d) {
      return TAB_OF[d.key] === 'items' && ITEM_ORDER.indexOf(d.key) === -1;
    }).map(function (d) { return d.key; }));
}

function renderItems() {
  const gs = itemGroups();
  let total = 0;
  for (const g of gs) total += (S.groups[g] || []).length;
  let h = '<div class="view">';
  h += searchHtml('Search items, gear, ammo, vehicles...');
  h += '<div class="chiprow">' +
    '<button class="fbtn' + (S.iGroup === 'all' ? ' on' : '') + '" data-igroup="all">All ' + total + '</button>' +
    gs.map(function (g) {
      return '<button class="fbtn' + (S.iGroup === g ? ' on' : '') + '" data-igroup="' + esc(g) + '">' +
        esc(groupTitle(g)) + '</button>';
    }).join('') + '</div>';
  if (S.iGroup !== 'all') {
    const cats = ['all'].concat(distinct(S.groups[S.iGroup] || [], 'category'));
    if (cats.length > 2) {
      h += '<div class="chiprow">' + cats.map(function (c) {
        return '<button class="fbtn' + (S.iCat === c ? ' on' : '') + '" data-icat="' + esc(c) + '">' +
          esc(c === 'all' ? 'All' : c) + '</button>';
      }).join('') + '</div>';
    }
  }
  /* Same reason as Weapons: the "All N" chip above is a count, not a roster. */
  h += rosterGapNoteHtml(gs);
  h += '<div class="row g8" style="margin-bottom:10px">' +
    '<button class="tbtn' + (S.onlyUnlockable ? ' on' : '') + '" data-unlockable>Hide what my WARDOG level ' + myLevel() + ' cannot buy</button></div>';
  h += '<div id="listRegion"></div>';
  h += '</div>';
  return h;
}

function itemRows() {
  const q = S.q.toLowerCase().trim();
  const gs = S.iGroup === 'all' ? itemGroups() : [S.iGroup];
  const out = [];
  for (const g of gs) {
    for (const e of (S.groups[g] || [])) {
      if (S.iGroup !== 'all' && S.iCat !== 'all' && e.category !== S.iCat) continue;
      if (S.onlyUnlockable && gatedAbove(e, myLevel())) continue;
      if (q && (nameOf(e, g) + ' ' + (e.category || '') + ' ' + (e.summary || '')).toLowerCase().indexOf(q) === -1) continue;
      out.push({ g: g, e: e });
    }
  }
  return out;
}

function fillItems() {
  const box = $('#listRegion');
  if (!box) return;
  const rows = itemRows();
  if (!rows.length) {
    box.innerHTML = '<div class="card muted">Nothing here matches. The dropdown above searches every other tab.</div>';
    return;
  }
  let h = '';
  let head = '';
  for (const r of rows) {
    const label = S.iGroup === 'all' ? groupTitle(r.g) : (r.e.category || groupTitle(r.g));
    if (label !== head) { head = label; h += '<h3 class="sh">' + esc(head) + '</h3>'; }
    h += '<button class="rowcard" data-ent="' + esc(keyOf(r.g, r.e.id)) + '">' +
      iconHtml(r.e, r.g, 44) +
      '<span class="rb"><span class="rn">' + esc(nameOf(r.e, r.g)) + '</span>' +
      '<span class="rm">' + esc(r.e.summary || '') + '</span></span>' +
      '<span class="rc">' + costChips(r.e) + '</span></button>';
  }
  box.innerHTML = h;
}

/* ------------------------------------------------------------- views: Builds */

/* THE TOOL TAB SHELL. The L2 generator (goals + enemy comp + locks + a receipt
   with its sample size per pick) is a later phase; this renders its slot, the
   profile/level state it will read, and the freshness + patch line the template
   requires on this tab specifically. When the pipeline adds a `builds` group to
   meta.json's wiki map, the generic loader picks it up, TAB_OF routes it here,
   and the starter-loadout section below renders it with no code change. */
function renderBuilds() {
  /* THE ONLY SEAM between app.js and the Builds lane. js/builds.js owns this
     tab (the L2 input surface, the picker and the receipts view) and registers
     window.WD_BUILDS. Everything below is the fallback that runs if that file
     is missing or threw - the app must not lose a tab over one script. */
  if (window.WD_BUILDS && typeof window.WD_BUILDS.render === 'function') return window.WD_BUILDS.render();

  const m = S.meta || {};
  let h = '<div class="view">';
  h += searchHtml('Search anything while you plan');

  h += '<h2 class="vh">Loadout builder</h2>';
  h += '<div class="card"><div class="fresh">' +
    '<span>Data pulled <b>' + esc(prettyDate(m.pulledAt)) + '</b></span><span class="faint">&middot;</span>' +
    '<span>Reflects <b>' + esc(m.pulledAtVersion || 'the Closed Beta') + '</b></span></div>' +
    '<p class="small muted" style="margin:8px 0 0">' + esc(m.disclaimer || '') + '</p></div>';

  h += '<div class="ruling">Anything this tab recommends is the best option it found in the numbers above, not a proof that nothing better exists. Where a pick has no sample behind it, it prints no number.</div>';

  h += '<h3 class="sh">Your profile</h3>';
  h += '<div class="card">';
  h += '<div class="lvlctl"><label for="lvl" class="small muted">WARDOG level</label>' +
    '<input id="lvl" type="number" min="1" max="200" inputmode="numeric" value="' + esc(myLevel()) + '" />' +
    '<span class="small faint">Filters every list to what you can actually unlock.</span></div>';
  h += '<div class="lvlctl" style="margin-top:12px"><label for="prof" class="small muted">Loadout</label>' +
    '<select id="prof" class="profsel">' + Object.keys(ST.profiles).map(function (id) {
      return '<option value="' + esc(id) + '"' + (id === ST.active ? ' selected' : '') + '>' + esc(ST.profiles[id].name) + '</option>';
    }).join('') + '</select>' +
    '<button class="tbtn" data-newprof>New</button>' +
    '<button class="tbtn" data-renprof>Rename</button>' +
    (Object.keys(ST.profiles).length > 1 ? '<button class="tbtn danger" data-delprof>Delete</button>' : '') +
    '</div>';
  h += '</div>';

  // Pins act as the working loadout until the generator lands.
  const pins = prof().pins.map(ent).filter(Boolean);
  h += '<h3 class="sh">Pinned (' + prof().pins.length + ')</h3>';
  if (!pins.length) {
    h += '<div class="card muted small">Nothing pinned yet. Open any weapon, attachment or vehicle and tap Pin to park it here while you plan a kit.</div>';
  } else {
    let cost = 0, weight = 0;
    for (const k of prof().pins) {
      const e = ent(k);
      if (!e) continue;
      if (typeof e.price === 'number') cost += e.price;
      if (typeof e.weightKg === 'number') weight += e.weightKg;
    }
    h += '<div class="card tight"><div class="fresh"><span>Total cost <b>' + esc(money(cost)) +
      '</b></span><span class="faint">&middot;</span><span>Carried weight <b>' +
      esc(Math.round(weight * 100) / 100) + ' kg</b></span></div>' +
      '<p class="small faint" style="margin:6px 0 0">Summed from the pinned entries that publish a price or a weight. Entries the source never priced are not counted.</p></div>';
    for (const k of prof().pins) {
      const e = ent(k);
      if (!e) continue;
      const gk = k.slice(0, k.indexOf(':'));
      h += '<button class="rowcard" data-ent="' + esc(k) + '">' + iconHtml(e, gk, 44) +
        '<span class="rb"><span class="rn">' + esc(nameOf(e, gk)) + '</span>' +
        '<span class="rm">' + esc(groupTitle(gk)) + (e.category ? ' &middot; ' + esc(e.category) : '') + '</span></span>' +
        '<span class="rc">' + costChips(e) + '</span></button>';
    }
  }

  // Forward-compatible: starter loadouts ship as data or not at all.
  if (Array.isArray(S.groups.builds) && S.groups.builds.length) {
    h += '<h3 class="sh">Starter loadouts</h3>';
    for (const b of S.groups.builds) {
      h += '<div class="card"><h4>' + esc(b.name || '') + '</h4>' +
        '<p class="small muted" style="margin:0">' + esc(b.summary || '') + '</p></div>';
    }
  } else {
    h += '<h3 class="sh">Generated loadouts</h3>';
    h += '<div class="mount-slot" id="buildsMount">The scored loadout generator is not built yet. ' +
      'When it lands it reads the level and the pinned kit above, and prints a receipt under every pick.</div>';
  }

  h += '</div>';
  return h;
}

/* --------------------------------------------------------------- views: More */

function renderMore() {
  const m = S.meta || {};
  let h = '<div class="view">';
  h += searchHtml('Search everything in WARDOGS');

  for (const gk of MORE_ORDER.concat(S.gmeta.filter(function (d) {
    return (TAB_OF[d.key] || 'more') === 'more' && MORE_ORDER.indexOf(d.key) === -1;
  }).map(function (d) { return d.key; }))) {
    const list = S.groups[gk] || [];
    if (!list.length) continue;
    h += '<h3 class="sh">' + esc(groupTitle(gk)) + ' (' + list.length + ')</h3>';
    if (gk === 'glossary') {
      h += '<div class="row wrap g6">' + list.map(function (t) {
        return '<button class="lchip" data-ent="' + esc(keyOf('glossary', t.id)) + '">' + esc(t.term) + '</button>';
      }).join('') + '</div>';
      continue;
    }
    for (const e of list) {
      h += '<button class="rowcard" data-ent="' + esc(keyOf(gk, e.id)) + '">' +
        iconHtml(e, gk, 44) +
        '<span class="rb"><span class="rn">' + esc(nameOf(e, gk)) + '</span>' +
        '<span class="rm">' + esc(firstSentences((e.beginner || {}).whatItIs, 1) || e.summary || '') + '</span></span>' +
        '</button>';
    }
  }

  h += '<h3 class="sh">Where this comes from</h3>';
  h += '<div class="card srcbox">';
  /* meta.licence is PIPELINE metadata - it records who took the risk decision
     and why, names a person, and is written for the vault, not for a player.
     It is deliberately NOT rendered: the user-facing statement is the
     attribution line (rendered once, in the footer / the shell's Attribution
     slot) plus the source list and the disclaimer below. */
  if (Array.isArray(m.sources)) {
    for (const s of m.sources) {
      h += '<p style="margin:0 0 6px"><b>' + esc(s.name) + '</b> &middot; ' + esc(s.use) + '<br />' +
        '<a href="' + esc(s.url) + '" target="_blank" rel="noopener noreferrer">' + esc(s.url) + '</a></p>';
    }
  }
  if (m.disclaimer) h += '<p style="margin:8px 0 0">' + esc(m.disclaimer) + '</p>';
  if (m.freshnessTrigger) h += '<p style="margin:8px 0 0">' + esc(m.freshnessTrigger) + '</p>';
  h += '</div>';

  h += rosterGapCardHtml();
  h += freshBlockHtml();
  h += '</div>';
  return h;
}

/* ------------------------------------------------ roster completeness ----- */

/* THE HONESTY SURFACE. This dataset is a PRE-RELEASE scrape and it is
   known-incomplete: the source's own prose names more weapons than it publishes
   cards for, and nothing guarantees the other groups are whole either. Every
   tab chip prints a bare count ("All 30"), and a bare count reads to a beginner
   as "this is the whole game" - which is the exact lie the vault wiki generated
   from the same meta.json does not tell.

   Everything below is DERIVED from data/meta.json.sourceClaims - there is no
   hardcoded roster number anywhere in this file. The day the data lane records
   a second gap (vehiclesClaimedBySource / vehiclesParsed /
   vehiclesClaimMatchesParsed, or any other group in that shape) it appears in
   the always-on banner, on Start, on the group tabs and on More with no change
   here. assertDisclosure() at the bottom of this block is the GATE that keeps
   it rendered rather than trusting a caller to remember. */

function rosterGaps() {
  const sc = (S.meta || {}).sourceClaims || {};
  const out = [];
  for (const key of Object.keys(sc)) {
    const m = /^(.+)ClaimedBySource$/.exec(key);
    if (!m) continue;
    const g = m[1];
    const claimed = sc[key];
    const parsed = sc[g + 'Parsed'];
    if (typeof claimed !== 'number' || typeof parsed !== 'number') continue;
    /* Only a DISAGREEMENT is a gap. An explicit true, or equal numbers, is the
       source and the payload agreeing and there is nothing to disclose. */
    if (sc[g + 'ClaimMatchesParsed'] === true || claimed === parsed) continue;
    out.push({ group: g, claimed: claimed, parsed: parsed, missing: claimed - parsed });
  }
  out.sort(function (a, b) { return b.missing - a.missing; });
  return out;
}

/* The one phrase every surface repeats verbatim, so assertDisclosure() can look
   for it and so the wording cannot drift between the banner and a tab. */
function gapPhrase(x) {
  return 'only ' + x.parsed + ' of the ' + x.claimed + ' ' +
    String(groupTitle(x.group)).toLowerCase() + ' the source names are published';
}

function rosterGapLine(gaps) {
  const g = gaps || rosterGaps();
  if (!g.length) {
    return 'This roster is incomplete: it holds only what the source published before Early Access.';
  }
  return 'This roster is incomplete - ' + g.map(gapPhrase).join(', ') + '.';
}

/* The short line for a group tab, under the chip row that prints the count.

   IT DOES NOT REPEAT THE GAP SENTENCE. The always-on banner above already
   carries gapPhrase() verbatim on every tab, and printing it a second time
   under the chips made the same sentence appear twice in one screenful - which
   reads as a rendering bug, not as emphasis. The banner owns the sentence; this
   line owns the thing the banner cannot say, which is what the chip's number
   means. assertDisclosure() below now asserts EXACTLY ONE occurrence per view,
   so neither surface can quietly take the other's job back. */
function rosterGapNoteHtml(groups) {
  const all = rosterGaps();
  const mine = groups && groups.length
    ? all.filter(function (g) { return groups.indexOf(g.group) !== -1; })
    : all;
  const txt = mine.length
    ? 'The number on the chip above is what this app can show, not the size of the roster - see the warning at the top of the screen.'
    : 'These are Closed Beta counts and the roster is incomplete: this app lists every entry the source published, which is not every entry in the game.';
  return '<div class="ruling">' + esc(txt) + '</div>';
}

/* The full disclosure card. Rendered on Start and on More. */
function rosterGapCardHtml() {
  const m = S.meta || {};
  const gaps = rosterGaps();
  const ci = m.coreIcons || {};
  let h = '<h3 class="sh">What is missing from this data</h3><div class="card">';
  /* Only when there is no recorded gap: with one, this card's per-gap paragraphs
     below say it in full, and the banner already carries the exact sentence.
     See rosterGapNoteHtml() - one occurrence per view, asserted after render. */
  if (!gaps.length) h += '<p style="margin:0">' + esc(rosterGapLine(gaps)) + '</p>';
  for (const g of gaps) {
    h += '<p class="small muted" style="margin:8px 0 0">The source\'s own text says WARDOGS has ' +
      g.claimed + ' ' + esc(String(groupTitle(g.group)).toLowerCase()) + ', but it only publishes ' +
      g.parsed + '. This app ships the ' + g.parsed +
      ' it can actually show and prints the gap instead of repeating a number it cannot back up.</p>';
  }
  h += '<p class="small muted" style="margin:8px 0 0">Groups with no gap listed above hold every entry the source published. That is not the same as every entry in the game. ' +
    esc(m.releaseStage || 'This is pre-release data.') +
    ' A full re-pull is owed on release day, so read every count on every tab as a Closed Beta count, not a final one.</p>';
  if (typeof ci.total === 'number' && typeof ci.placeholders === 'number' && ci.placeholders) {
    h += '<p class="small muted" style="margin:8px 0 0">' + ci.placeholders + ' of ' + ci.total +
      ' entries also show a plain stand-in icon, because the source hosts no artwork for them.</p>';
  }
  h += '</div>';
  return h;
}

/* THE GATE (R5). The disclosure is asserted after every render, not trusted to
   a caller. If a future edit drops the calls above, or the data lane records a
   gap that no view happens to print, the phrase is absent from the rendered
   page and this puts it back into the always-on banner and logs it - so an
   omission is loud instead of silent. It can only ADD a disclosure, never
   remove one. Returns true when the page already disclosed every gap. */
function assertDisclosure() {
  const gaps = rosterGaps();
  if (!gaps.length) return true;
  let seen = '';
  try {
    const a = app();
    const b = $('#prebar');
    seen = (a ? (a.innerText || a.textContent || '') : '') + ' ' +
      (b ? (b.innerText || b.textContent || '') : '');
  } catch (e) { return true; }
  if (!seen.trim()) return true; // nothing rendered yet; nothing to judge
  const low = seen.toLowerCase();
  const missing = gaps.filter(function (g) { return low.indexOf(gapPhrase(g)) === -1; });
  /* EXACTLY ONCE, not at least once. Round 4 found the banner and the Weapons
     tab both printing the identical sentence a few hundred pixels apart. A
     disclosure that repeats itself reads as a bug and trains the eye to skip it,
     so a second occurrence is a defect the same way a missing one is - it just
     cannot be repaired from here, since only the view that printed it knows
     where it came from. Loud, and it fails the assertion. */
  const dupes = gaps.filter(function (g) {
    const p = gapPhrase(g);
    let n = 0, i = low.indexOf(p);
    while (i !== -1) { n++; i = low.indexOf(p, i + p.length); }
    return n > 1;
  });
  if (dupes.length) {
    try {
      console.warn('[wardogs] roster-gap disclosure is printed more than once on this view: ' +
        dupes.map(gapPhrase).join(' | ') + '. The banner owns the sentence; a view must not repeat it.');
    } catch (e) { /* no-op */ }
    return false;
  }
  if (!missing.length) return true;
  const bar = $('#prebar');
  if (bar) {
    bar.innerHTML = '<div class="pb"><span class="pbi">&#9888;</span><span>' +
      esc(rosterGapLine(missing)) + '</span></div>';
  }
  try {
    console.warn('[wardogs] roster-gap disclosure was missing from the rendered page; restored it in the banner.');
  } catch (e) { /* no-op */ }
  return false;
}

/* ----------------------------------------------------------------- shared */

function freshBlockHtml() {
  const m = S.meta || {};
  const c = m.counts || {};
  let total = 0;
  for (const k of Object.keys(c)) total += c[k];
  return '<h3 class="sh">Freshness</h3><div class="card"><div class="fresh">' +
    '<span>Pulled <b>' + esc(prettyDate(m.pulledAt)) + '</b></span><span class="faint">&middot;</span>' +
    '<span>Reflects <b>' + esc(m.pulledAtVersion || '') + '</b></span><span class="faint">&middot;</span>' +
    '<span><b>' + total + '</b> entries</span></div>' +
    '<p class="small muted" style="margin:8px 0 0">' + esc(m.releaseStage || '') + ' ' + esc(m.disclaimer || '') + '</p>' +
    /* The entry total sits directly above this line on purpose: a total is not
       a roster, and this line says so. It does NOT repeat gapPhrase() - the
       always-on banner carries that sentence on every tab, and this block is
       rendered on Start, More and the Builds fallback, so repeating it put the
       identical sentence on screen twice. When there is no recorded gap the
       generic line is the only place it appears and is printed in full. */
    '<p class="small muted" style="margin:8px 0 0">' +
    esc(rosterGaps().length
      ? 'That total is what this app can show, not the size of the roster - the warning at the top of the screen says what is missing.'
      : rosterGapLine()) + '</p></div>';
}

function prettyDate(iso) {
  if (!iso) return 'unknown';
  const d = new Date(iso);
  if (isNaN(d.getTime())) return String(iso);
  const mo = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
  return d.getUTCDate() + ' ' + mo[d.getUTCMonth()] + ' ' + d.getUTCFullYear();
}

/* Only a NUMERIC wardogLevel can be compared against the account level. A
   class-gated entry ("Recon Lvl 25") is left visible rather than hidden on a
   comparison the data does not support. */
function gatedAbove(e, lvl) {
  return typeof e.wardogLevel === 'number' && e.wardogLevel > lvl;
}

function distinct(list, field) {
  const seen = [];
  for (const e of list) {
    const v = e[field];
    if (v && seen.indexOf(v) === -1) seen.push(v);
  }
  return seen;
}

function renderPreBanner() {
  const el = $('#prebar');
  if (!el) return;
  const m = S.meta || {};
  /* The roster-gap line rides the ALWAYS-ON banner, which is the only chrome
     that survives the shell stripping the header and is present on all five
     tabs including Builds (a tab this file does not render). It is the floor
     assertDisclosure() checks against. */
  const txt = (m.releaseStage ? m.releaseStage + ' ' : '') + (m.disclaimer || '') +
    ' ' + rosterGapLine();
  if (!txt.trim()) { el.innerHTML = ''; return; }
  el.innerHTML = '<div class="pb"><span class="pbi">&#9888;</span><span>' + esc(txt) + '</span></div>';
}

/* --------------------------------------------------------------- rendering */

const VIEWS = {
  start: renderStart, weapons: renderWeapons, items: renderItems,
  builds: renderBuilds, more: renderMore
};

function render() {
  const a = app();
  if (!a) return;
  const fn = VIEWS[S.view] || renderStart;
  a.innerHTML = fn();
  if (S.view === 'weapons') fillWeapons();
  if (S.view === 'items') fillItems();
  renderSuggest();
  const tabs = document.querySelectorAll('#tabbar .tab');
  for (let i = 0; i < tabs.length; i++) {
    tabs[i].classList.toggle('on', tabs[i].getAttribute('data-view') === S.view);
  }
  /* R5 gate, last thing every render does: prove the roster-gap disclosure is
     actually on the page (including on Builds, which another lane renders) and
     put it back in the banner if it is not. */
  assertDisclosure();
}

function go(view) {
  if (!VIEWS[view]) view = 'start';
  if (S.view !== view) { S.view = view; S.q = ''; }
  render();
  try { window.scrollTo(0, 0); } catch (e) { /* no-op */ }
  setHash('#/' + view);
}

/* -------------------------------------------------------------- hash router */

/* The app owns the hash (registry nativeHashRouting: true). A hash WE wrote
   must not bounce back through applyHash, and a timer-based guard races the
   browser's own hashchange dispatch - so compare the value instead. */
let selfHash = null;
function setHash(h) {
  if (location.hash === h) return;
  selfHash = h;
  try { location.hash = h; } catch (e) { selfHash = null; }
}

function applyHash() {
  const raw = (location.hash || '').replace(/^#\/?/, '');
  const parts = raw.split('/').filter(Boolean);
  if (!parts.length) { S.view = 'start'; render(); return; }
  if (parts[0] === 'e' && parts.length >= 3) {
    const k = parts[1] + ':' + parts.slice(2).join(':');
    if (ent(k)) {
      const tab = TAB_OF[parts[1]] || 'more';
      if (S.view !== tab) { S.view = tab; }
      render();
      openEntity(k);
      return;
    }
  }
  if (VIEWS[parts[0]]) { S.view = parts[0]; render(); return; }
  S.view = 'start';
  render();
}

/* ------------------------------------------------------------------ events */

document.addEventListener('click', function (ev) {
  const t = ev.target;
  if (!t || !t.closest) return;

  const close = t.closest('[data-close]');
  if (close) { closeSheet(); return; }

  const entBtn = t.closest('[data-ent]');
  if (entBtn) { openEntity(entBtn.getAttribute('data-ent')); return; }

  const tab = t.closest('#tabbar .tab');
  if (tab) { if (sheetOpen) closeSheet(); go(tab.getAttribute('data-view')); return; }

  const goto = t.closest('[data-goto]');
  if (goto) { if (sheetOpen) closeSheet(); go(goto.getAttribute('data-goto')); return; }

  const wcat = t.closest('[data-wcat]');
  if (wcat) { S.wCat = wcat.getAttribute('data-wcat'); render(); return; }

  const igroup = t.closest('[data-igroup]');
  if (igroup) { S.iGroup = igroup.getAttribute('data-igroup'); S.iCat = 'all'; render(); return; }

  const icat = t.closest('[data-icat]');
  if (icat) { S.iCat = icat.getAttribute('data-icat'); render(); return; }

  if (t.closest('[data-unlockable]')) { S.onlyUnlockable = !S.onlyUnlockable; render(); return; }

  if (t.closest('[data-clearq]')) { S.q = ''; render(); return; }

  const grp = t.closest('[data-group]');
  if (grp) {
    const g = grp.getAttribute('data-group');
    if (sheetOpen) closeSheet();
    const tabName = TAB_OF[g] || 'more';
    if (tabName === 'items') { S.iGroup = g; S.iCat = 'all'; }
    go(tabName);
    return;
  }

  const fits = t.closest('[data-fits]');
  if (fits) {
    const w = (S.groups.weapons || []).filter(function (x) { return x.id === fits.getAttribute('data-fits'); })[0];
    if (w) {
      closeSheet();
      S.iGroup = 'attachments'; S.iCat = 'all'; S.q = '';
      go('items');
      const box = $('#listRegion');
      if (box) {
        const list = attachmentsFor(w);
        box.innerHTML = '<h3 class="sh">Listed as fitting ' + esc(w.name) + ' (' + list.length + ')</h3>' + list.map(function (a) {
          return '<button class="rowcard" data-ent="' + esc(keyOf('attachments', a.id)) + '">' +
            iconHtml(a, 'attachments', 44) +
            '<span class="rb"><span class="rn">' + esc(a.name) + '</span>' +
            '<span class="rm">' + esc(a.summary || '') + '</span></span>' +
            '<span class="rc">' + costChips(a) + '</span></button>';
        }).join('');
      }
    }
    return;
  }

  const pin = t.closest('[data-pin]');
  if (pin) {
    const k = pin.getAttribute('data-pin');
    const on = togglePin(k);
    pin.classList.toggle('on', on);
    pin.textContent = on ? 'Pinned' : 'Pin';
    return;
  }

  const own = t.closest('[data-own]');
  if (own) {
    const k = own.getAttribute('data-own');
    toggleOwned(k);
    const on = isOwned(k);
    own.classList.toggle('on', on);
    own.textContent = on ? 'Unlocked' : 'Mark unlocked';
    return;
  }

  if (t.closest('[data-newprof]')) {
    const nm = window.prompt('Name this loadout', 'Loadout ' + (Object.keys(ST.profiles).length + 1));
    if (nm) {
      const id = 'p' + Date.now().toString(36);
      ST.profiles[id] = blankProfile(nm.slice(0, 40));
      ST.active = id;
      saveState();
      render();
    }
    return;
  }
  if (t.closest('[data-renprof]')) {
    const nm = window.prompt('Rename this loadout', prof().name);
    if (nm) { prof().name = nm.slice(0, 40); saveState(); render(); }
    return;
  }
  if (t.closest('[data-delprof]')) {
    if (Object.keys(ST.profiles).length > 1 && window.confirm('Delete "' + prof().name + '"?')) {
      delete ST.profiles[ST.active];
      ST.active = Object.keys(ST.profiles)[0];
      saveState();
      render();
    }
    return;
  }
});

document.addEventListener('input', function (ev) {
  const t = ev.target;
  if (!t) return;
  if (t.id === 'q') {
    S.q = t.value || '';
    if (S.view === 'weapons') fillWeapons();
    if (S.view === 'items') fillItems();
    renderSuggest();
    return;
  }
  if (t.id === 'lvl') {
    const n = parseInt(t.value, 10);
    if (isFinite(n) && n > 0) setMyLevel(Math.min(n, 200));
    return;
  }
});

document.addEventListener('change', function (ev) {
  const t = ev.target;
  if (t && t.id === 'prof' && ST.profiles[t.value]) {
    ST.active = t.value;
    saveState();
    render();
  }
});

document.addEventListener('keydown', function (ev) {
  if (ev.key === 'Escape' && sheetOpen) closeSheet();
});

window.addEventListener('hashchange', function () {
  if (selfHash !== null && location.hash === selfHash) { selfHash = null; return; }
  selfHash = null;
  if (!S.booted) return;
  if (sheetOpen) { const sh = $('#sheet'); if (sh) sh.hidden = true; sheetOpen = false; try { document.body.style.overflow = ''; } catch (e) { } }
  applyHash();
});

/* -------------------------------------------------------------------- boot */

function fetchJson(path) {
  return fetch(path, { cache: 'no-cache' }).then(function (r) {
    if (!r.ok) throw new Error(path + ' -> HTTP ' + r.status);
    return r.json();
  });
}

function boot() {
  ST = loadState();
  const a = app();
  if (a) a.innerHTML = '<div class="boot">Loading WARDOGS data...</div>';

  fetchJson('/island/apps/wardogs/data/meta.json').then(function (meta) {
    S.meta = meta;
    const wiki = meta.wiki || {};
    S.gmeta = Object.keys(wiki).map(function (k) {
      return { key: k, title: wiki[k].title || k, nameField: wiki[k].nameField || 'name', file: wiki[k].file || (k + '.json') };
    });
    if (!S.gmeta.length) throw new Error('meta.json has no wiki group map');
    for (const d of S.gmeta) S.gmap[d.key] = d;
    return Promise.all(S.gmeta.map(function (d) {
      return fetchJson('/island/apps/wardogs/data/' + d.file).then(function (rows) {
        S.groups[d.key] = Array.isArray(rows) ? rows : [];
      });
    }));
  }).then(function () {
    for (const d of S.gmeta) {
      for (const e of S.groups[d.key]) {
        const k = keyOf(d.key, e.id);
        S.byId[k] = e;
        const nm = String(nameOf(e, d.key) || '').toLowerCase();
        if (nm && !S.byName[nm]) S.byName[nm] = k;
      }
    }
    buildIndex();
    const pill = $('#patchPill');
    if (pill && S.meta.pulledAtVersion) pill.textContent = S.meta.pulledAtVersion;
    const foot = $('#footNote');
    if (foot && S.meta.attribution) foot.textContent = S.meta.attribution;
    renderPreBanner();
    S.booted = true;
    applyHash();
    warmSprites();
  }).catch(function (err) {
    const el = app();
    if (el) {
      el.innerHTML = '<div class="boot err">Could not load the WARDOGS dataset.<br />' +
        esc(err && err.message ? err.message : String(err)) +
        '<br /><span class="small faint">If you are offline and this app was never opened online, there is nothing cached yet.</span></div>';
    }
  });
}

/* ------------------------------------------------------ offline sprite warm */
/* Every entity icon is a LOCAL file under sprites/ (meta.coreIcons:
   withLocalIcon 214, missing 0), but LOCAL is not CACHED. The shell's service
   worker stores an image the moment something requests it and not a moment
   before, so an installed PWA held only the icons the viewer had already
   scrolled past: the round-3 browser verifier measured 112 of 214 resident
   after a full online sweep of all five tabs, and offline every other icon
   threw "TypeError: Failed to fetch" and fell through to wdSprErr()'s '?'
   tile. Downloading the sprites locally was supposed to buy offline; without
   this it bought nothing.

   registry.spriteWarm (see the wardogs block in the shell registry) gives this
   route its own cache bucket, cache-first and exempt from the shared image
   LRU's 2,000-ENTRY cap. That is only half of it - the bucket changes WHERE a
   fetched sprite lands, it pre-fetches nothing. This is the other half: the
   app names the files, the worker does the caching.

   The APP owns the list because only the app has data/*.json parsed. It posts
   BARE FILENAMES and the worker resolves them against its own sprite dir. One
   tier, 'icons': there is no mode split here (unlike Terraria's
   vanilla/calamity) because the whole 214-file / 7.4 MB set is core. The
   worker fetches it 24 at a time in the background and writes a completion
   marker keyed to `stamp`, so it runs once per dataset and a partial warm is
   retried on the next load. */

/* Two path shapes reach us and both must reduce to a bare filename:
     standalone  "/island/apps/wardogs/sprites/ammo-12-gauge.svg"        (what data/*.json ships)
     mounted     "/island/apps/wardogs/sprites/..."   (assemble rewrites it)
   Strip through the LAST "sprites/" with a greedy .*, which covers both and
   any future mount prefix. A sprite filename can never contain a slash, so a
   result that still does is quarantined into `unresolved` and never posted -
   a new path shape then shows up as an empty warm rather than as ~214
   silently-404ing requests on every page load. */
const SPRITE_BASE_RE = /^.*\/?sprites\//;
function spriteFile(p) { return String(p == null ? '' : p).replace(SPRITE_BASE_RE, ''); }

let SPRITE_WARM = null;
function spriteWarmPayload() {
  if (SPRITE_WARM) return SPRITE_WARM;
  const files = new Set(), bad = new Set();
  for (const d of S.gmeta) {
    for (const e of (S.groups[d.key] || [])) {
      if (!e || !e.icon) continue;
      const f = spriteFile(e.icon);
      if (!f || f.indexOf('/') !== -1) { bad.add(String(e.icon)); continue; }
      files.add(f);
    }
  }
  const m = S.meta || {};
  SPRITE_WARM = {
    files: Array.from(files),
    unresolved: Array.from(bad),
    // Changes whenever the dataset is re-pulled (the Early Access re-pull
    // owed 2026-09-10 will move it), which is what re-warms the new sprites.
    stamp: (m.pulledAt || '') + ':' + ((m.sprites && m.sprites.onDisk) || 0) + ':' + files.size
  };
  return SPRITE_WARM;
}

/* boot()'s data fetch and the service-worker handshake race each other, so
   BOTH sides call this and it no-ops until both halves are ready. Whichever
   finishes last is the one that actually posts. */
let SW_TARGET = null;
function warmSprites() {
  if (!SW_TARGET || !S.booted) return;
  try {
    const p = spriteWarmPayload();
    if (!p.files.length) return;
    SW_TARGET.postMessage({ type: 'warm-sprites', stamp: p.stamp, tiers: [['icons', p.files]] });
  } catch (e) { }
}
if ('serviceWorker' in navigator) {
  /* This app still REGISTERS nothing - the shell owns exactly one worker (see
     the PORT NOTES at the top of this file). It only waits for whichever
     worker already controls this page. Served standalone with no worker at
     all, `ready` never settles and this is simply a no-op. */
  navigator.serviceWorker.ready.then(function (reg) {
    SW_TARGET = navigator.serviceWorker.controller || (reg && reg.active);
    warmSprites();
  }).catch(function () { });
}

if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', boot);
else boot();
