/* Path of Exile 2 Companion - vanilla JS, no build step, no modules.
 *
 * Data: data/meta.json + one JSON per entity group, all generated by
 * tools/build_data.mjs. THIS FILE HAND-WRITES NO GAME PROSE. Every sentence a
 * user reads about an entity comes out of `beginner.{whatItIs,whyItMatters,
 * whenToUseIt}` in the data, which the pipeline merges forward from
 * tools/beginner-notes/. Chrome labels ("Classes", "Your first 10 minutes")
 * are UI, not game facts.
 *
 * WHAT IS DELIBERATELY NOT RENDERED, and why:
 *  - `description` on every group. It is either a duplicate of
 *    beginner.whatItIs (classes, bosses) or a concatenation of the stat lines
 *    that are already rendered as a modifier list (uniques, currency, gems).
 *    Rendering it would print the same facts twice and widen the amount of
 *    source-derived text on screen for nothing.
 *  - `flavourText` on uniques, gems and ascendancies. That is Grinding Gear
 *    Games' own creative writing, the one string in this dataset with no
 *    mechanical content. The app renders mechanical game data plus its own
 *    beginner prose; it does not republish flavour writing.
 *  - `variants[]`. The pull stores collapsed variant rows with their raw
 *    MediaWiki payload intact, including literal <table class="..."> markup.
 *    See cleanMods() below - the same guard also filters 63 junk lines that
 *    reached explicitStats on 20 unique items.
 *
 * PORT NOTES (fiiiish-app shell):
 *  - The shell strips #topbar and #siteFoot. Every lookup into either is
 *    null-guarded, so a stripped id is a no-op, not a crash.
 *  - This app owns location.hash -> the registry entry must set
 *    nativeHashRouting: true. The shared shim fires synchronously and would
 *    lose the race against the data fetch.
 *  - No service worker is registered here. The shell owns exactly one. The
 *    block at the bottom of this file only WAITS for whichever worker already
 *    controls the page and posts it the sprite-warm list - that is the app
 *    half of registry.spriteWarm and it must not be removed. Standalone, with
 *    no worker, it no-ops.
 *  - No absolute deploy URL anywhere. All app assets are '/island/apps/poe2/'-relative; the
 *    icon paths inside data/*.json need registry.assetPrefixes: ['/island/apps/poe2/sprites/']
 *    (see README.md, checklist line 2).
 */
'use strict';

/* ------------------------------------------------------------------ state */

const S = {
  meta: null,
  groups: {},        // key -> [entities]
  gmeta: [],         // ordered group descriptors (from meta.wiki)
  gmap: {},          // key -> descriptor
  byId: {},          // "group:id" -> entity
  byName: {},        // lowercased display name -> "group:id"
  index: [],         // search index rows
  view: 'start',
  q: '',
  cAttr: 'all',      // Classes tab: attribute filter
  cPlayable: false,  // Classes tab: only classes the data marks playable
  iGroup: 'all',     // Items tab: entity group
  iCat: 'all',       // Items tab: category within that group
  iTier: 'all',      // Items tab: gem tier within that group
  onlyUsable: false, // hide entities whose required level is above mine
  mSec: 'bosses',    // More tab: which section
  mCat: 'all',       // More tab: boss type filter
  limit: 60,         // incremental list cap
  booted: false
};

const $ = sel => document.querySelector(sel);
const app = () => $('#app');
const esc = s => String(s == null ? '' : s).replace(/[&<>"']/g, c => ({
  '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;'
}[c]));

const PAGE_SIZE = 60;

/* Which of the five tabs each entity group lives on. A group the pipeline adds
   later and this map has not heard of lands on More rather than vanishing.
   Skill gems and support gems sit on Items because that is what they are in
   Path of Exile 2 - inventory items you socket - and because the Items tab is
   the one the template defines as "filtered by category and tier", which is
   exactly how gems are sorted (primary attribute, gem tier). */
const TAB_OF = {
  classes: 'classes',
  skillGems: 'items', supportGems: 'items', uniques: 'items', currency: 'items',
  bosses: 'more', glossary: 'more', mechanics: 'more',
  builds: 'builds'
};
const ITEM_ORDER = ['skillGems', 'supportGems', 'uniques', 'currency'];
const MORE_ORDER = ['bosses', 'glossary', 'mechanics'];

/* The Start walkthrough is an ORDERED SELECTION of existing glossary entries,
   not new prose: the words a brand-new exile meets, in the order the game
   introduces them. Anything that does not resolve is dropped, so a pipeline
   rename shortens the list instead of rendering a dead step. */
const START_STEPS = [
  'glossary:class',
  'glossary:attribute',
  'glossary:skill-gem',
  'glossary:uncut-gem',
  'glossary:gem-socket',
  'glossary:support-gem',
  'glossary:currency-item',
  'glossary:rarity',
  'glossary:resistance',
  'glossary:checkpoint',
  'glossary:dodge-roll',
  'glossary:ascendancy'
];

/* ------------------------------------------------------- persistence layer */

/* ONE namespaced key holding the whole blob. The name deliberately contains no
   "token", "auth" or "secret" and does not start with "sb-": import.astro's
   CREDENTIAL regex is tested BEFORE its allowlist and would silently drop this
   key from every backup and restore (R11 - do not relax the regex, rename the
   key). Multi-profile from day one; retrofitting profiles orphans saved data. */
const LS_KEY = 'poe2_companion_v1';

let ST = null;          // the whole blob
let saveTimer = null;

function blankProfile(name) {
  return { name: name || 'Character 1', manual: {}, imported: {}, pins: [], synced_at: null };
}
function blankState() {
  return { v: 1, active: 'p1', profiles: { p1: blankProfile('Character 1') } };
}

function loadState() {
  try {
    const raw = localStorage.getItem(LS_KEY);
    if (!raw) return blankState();
    const o = JSON.parse(raw);
    if (!o || typeof o !== 'object' || !o.profiles || typeof o.profiles !== 'object') return blankState();
    for (const id of Object.keys(o.profiles)) {
      const p = o.profiles[id];
      if (!p || typeof p !== 'object') { delete o.profiles[id]; continue; }
      if (typeof p.name !== 'string') p.name = 'Character';
      if (!p.manual || typeof p.manual !== 'object') p.manual = {};
      if (!p.imported || typeof p.imported !== 'object') p.imported = {};
      if (!Array.isArray(p.pins)) p.pins = [];
    }
    if (!Object.keys(o.profiles).length) return blankState();
    if (!o.profiles[o.active]) o.active = Object.keys(o.profiles)[0];
    o.v = 1;
    return o;
  } catch (e) {
    return blankState();
  }
}

function showSave(kind) {
  const el = $('#savePill');
  if (!el) return;
  el.hidden = false;
  el.className = 'save-pill' + (kind === 'saved' ? ' ok' : kind === 'failed' ? ' bad' : '');
  el.textContent = kind === 'saving' ? 'saving...' : kind === 'saved' ? 'saved' : 'save failed';
  if (kind === 'saved') {
    setTimeout(function () {
      const e2 = $('#savePill');
      if (e2 && e2.textContent === 'saved') e2.hidden = true;
    }, 1400);
  }
}

/* 300 ms debounced write behind a visible pill. Never write synchronously per
   click - a fast tapper would hit localStorage on every keystroke. */
function saveState() {
  showSave('saving');
  if (saveTimer) clearTimeout(saveTimer);
  saveTimer = setTimeout(function () {
    saveTimer = null;
    try {
      localStorage.setItem(LS_KEY, JSON.stringify(ST));
      showSave('saved');
    } catch (e) {
      showSave('failed');
    }
  }, 300);
}

function prof() {
  if (!ST) ST = blankState();
  if (!ST.profiles[ST.active]) ST.active = Object.keys(ST.profiles)[0];
  return ST.profiles[ST.active];
}

/* Sparse manual-override layer over imported data. A read falls through
   manual -> imported; a write whose value EQUALS the imported value deletes the
   manual key, so the override layer only ever holds real divergence and a
   future import is not fought by a stale local edit. */
function impGet(p, group, key) {
  const g = p.imported && p.imported[group];
  return g ? g[key] : undefined;
}
function ovGet(p, group, key, dflt) {
  const m = p.manual && p.manual[group];
  if (m && Object.prototype.hasOwnProperty.call(m, key)) return m[key];
  const iv = impGet(p, group, key);
  return iv === undefined ? dflt : iv;
}
function ovSet(group, key, val) {
  const p = prof();
  const iv = impGet(p, group, key);
  if (!p.manual) p.manual = {};
  if (val === iv || (iv === undefined && (val === false || val === null))) {
    if (p.manual[group]) {
      delete p.manual[group][key];
      if (!Object.keys(p.manual[group]).length) delete p.manual[group];
    }
  } else {
    if (!p.manual[group]) p.manual[group] = {};
    p.manual[group][key] = val;
  }
  saveState();
}

function myLevel() {
  const v = ovGet(prof(), 'meta', 'level', 1);
  const n = parseInt(v, 10);
  return isFinite(n) && n > 0 ? n : 1;
}
function setMyLevel(n) { ovSet('meta', 'level', n); }
function myClass() { return ovGet(prof(), 'meta', 'class', '') || ''; }
function setMyClass(id) { ovSet('meta', 'class', id || ''); }
function isPinned(k) { const p = prof(); return p.pins.indexOf(k) !== -1; }
function togglePin(k) {
  const p = prof();
  const i = p.pins.indexOf(k);
  if (i >= 0) p.pins.splice(i, 1); else p.pins.push(k);
  saveState();
  return i < 0;
}

/* ------------------------------------------------------------- formatting */

const LABELS = {
  requiredLevel: 'Required level', dropLevel: 'Drops from level',
  gemTier: 'Gem tier', gemType: 'Gem type', primaryAttribute: 'Primary attribute',
  maxLevel: 'Maximum gem level', castTime: 'Cast time', radius: 'Radius',
  projectileSpeed: 'Projectile speed', weaponRestriction: 'Needs weapon',
  itemClass: 'Item class', baseItem: 'Base item',
  stackSize: 'Stack size', stackSizeCurrencyTab: 'Stack size in the currency tab',
  usage: 'How to use it', releaseVersion: 'Added in',
  weaponFocus: 'Weapon focus', startingGear: 'Starts with',
  bossTypes: 'Where it is fought', levels: 'Monster level', locations: 'Found in',
  resistances: 'Resists', weaknesses: 'Weak to', damageTypes: 'Deals',
  modifiers: 'Modifiers', quest: 'Quest', skillNames: 'Attacks',
  armour: 'Armour', evasion: 'Evasion', energyShield: 'Energy shield',
  ward: 'Ward', movementSpeed: 'Movement speed',
  playable: 'Playable in the current build',
  unreleased: 'Announced but not in the game yet',
  skillsPartial: 'Attack list is incomplete',
  skillsPartialReason: 'Why the attack list is incomplete'
};

/* Keys never shown as a stat row: identity, plumbing, licence-sensitive, or
   rendered somewhere better by hand. See the header comment for the reasoning
   behind description / flavourText / variants. */
const SKIP = ['id', 'name', 'term', 'page', 'wiki', 'beginner', 'icon', 'iconTarget',
  'iconIsPlaceholder', 'iconPlaceholderReason', 'skillIcon', 'skillIconTarget',
  'description', 'flavourText', 'variants', 'tags', 'seeAlso', 'ascendancies',
  'stats', 'skillStats', 'explicitStats', 'implicitStats', 'effect', 'baseStats',
  'attributes', 'primaryAttributes', 'requirements', 'gemTags', 'category',
  'families', 'itemClassId', 'baseItemWiki', 'skillId', 'attributeSplit',
  'isVaal', 'isAwakened', 'isReplica', 'skillNames', 'modifiers',
  'startingGear', 'randomModifierPool',
  /* both are rendered as a chip plus a sentence in the sheet, not as a Yes row */
  'unreleased', 'skillsPartial', 'skillsPartialReason'];

const ATTR_NAME = { str: 'Strength', dex: 'Dexterity', int: 'Intelligence' };
const ATTR_KEY = { strength: 'str', dexterity: 'dex', intelligence: 'int' };

function attrLabel(a) {
  if (!a || a === 'none') return 'No attribute';
  const s = String(a);
  return s.charAt(0).toUpperCase() + s.slice(1);
}
function attrCls(a) {
  const k = ATTR_KEY[String(a)] || String(a);
  return k === 'str' || k === 'dex' || k === 'int' ? k : '';
}

/* "verisium_common" -> "Verisium common". Pure UI formatting of an id the
   source publishes in snake_case; it invents nothing. */
function prettyCat(v) {
  if (!v) return '';
  const s = String(v).replace(/_/g, ' ');
  return s.charAt(0).toUpperCase() + s.slice(1);
}
function bossTypeLabel(t) {
  if (!t) return 'Boss';
  const s = String(t);
  if (/^act-/.test(s)) return 'Act ' + s.slice(4);
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function fmtVal(key, v) {
  if (v === null || v === undefined || v === '') return '';
  if (typeof v === 'boolean') return v ? 'Yes' : 'No';
  if (Array.isArray(v)) {
    return v.map(function (x) {
      if (x && typeof x === 'object') return x.name || '';
      if (key === 'bossTypes') return bossTypeLabel(x);
      return String(x);
    }).filter(Boolean).join(', ');
  }
  if (key === 'primaryAttribute') return attrLabel(v);
  if (key === 'gemType') return prettyCat(v);
  if (key === 'castTime') return v === 0 ? 'Instant' : v + ' seconds';
  if (key === 'movementSpeed' && typeof v === 'number') return v === 0 ? '0' : String(v);
  return String(v);
}
function labelOf(key) {
  if (LABELS[key]) return LABELS[key];
  return key.replace(/([A-Z])/g, ' $1').replace(/^./, function (c) { return c.toUpperCase(); });
}

/* Split on sentence ends WITHOUT a lookbehind - Safari only shipped lookbehind
   in 16.4 and a regex the parser rejects takes the whole file down. */
function firstSentences(text, n) {
  if (!text) return '';
  const s = String(text);
  const want = n || 1;
  let out = '', count = 0, i = 0;
  while (i < s.length) {
    out += s[i];
    if ('.!?'.indexOf(s[i]) !== -1 && (i + 1 >= s.length || /\s/.test(s[i + 1]))) {
      count++;
      if (count >= want) break;
    }
    i++;
  }
  return out.trim();
}

function prettyDate(iso) {
  if (!iso) return 'unknown';
  const d = new Date(iso);
  if (isNaN(d.getTime())) return String(iso);
  const mo = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
  return d.getUTCDate() + ' ' + mo[d.getUTCMonth()] + ' ' + d.getUTCFullYear();
}

/* THE TEMPLATE-JUNK GUARD (the Terraria dv()/dvText() lesson, applied here).
   The unique-item pull carried 63 modifier lines on 20 items straight out of
   MediaWiki with their markup intact - literal <table class="random-modifier-
   stats"> fragments. Escaped, those render as a wall of visible angle
   brackets; unescaped they would inject markup. Neither is acceptable, so a
   line carrying any template or HTML syntax is DROPPED and the count of what
   was dropped is stated on the sheet rather than hidden. */
const TPL_JUNK = /<[a-z!\/]|\{\{|\}\}|\[\[|\]\]|class\s*=|link\s*=|\d+\s*x\s*\d+\s*px/i;
function cleanMods(list) {
  const out = { lines: [], dropped: 0 };
  if (!Array.isArray(list)) return out;
  for (const s of list) {
    if (typeof s !== 'string') continue;
    const t = s.trim();
    if (!t) continue;
    if (TPL_JUNK.test(t)) { out.dropped++; continue; }
    out.lines.push(t);
  }
  return out;
}

/* --------------------------------------------------------------- entities */

function nameOf(e, gk) {
  const d = S.gmap[gk];
  const nf = (d && d.nameField) || 'name';
  return e[nf] || e.name || e.term || e.id;
}
function keyOf(gk, id) { return gk + ':' + id; }
function ent(k) { return S.byId[k] || null; }
function groupTitle(gk) { const d = S.gmap[gk]; return (d && d.title) || gk; }
function groupOf(k) { const i = k.indexOf(':'); return i < 0 ? '' : k.slice(0, i); }

function resolveName(name) {
  if (!name) return null;
  return S.byName[String(name).toLowerCase().trim()] || null;
}

/* The one value a list row, a grid card and a filter chip all agree on. */
function catOf(gk, e) {
  if (gk === 'skillGems' || gk === 'supportGems') return attrLabel(e.primaryAttribute);
  if (gk === 'uniques') return e.itemClass || '';
  if (gk === 'currency') return prettyCat(e.category);
  if (gk === 'bosses') return bossTypeLabel((e.bossTypes || [])[0]);
  if (gk === 'classes') return (e.primaryAttributes || []).map(function (a) { return ATTR_NAME[a] || a; }).join(' + ');
  return e.category || '';
}
function tierOf(e) { return typeof e.gemTier === 'number' ? e.gemTier : null; }
function reqLevelOf(e) { return typeof e.requiredLevel === 'number' ? e.requiredLevel : null; }

/* Only an entity that PUBLISHES a required level can be compared against the
   character level. Everything else stays visible rather than being hidden on a
   comparison the data does not support. */
function gatedAbove(e, lvl) {
  const r = reqLevelOf(e);
  return r !== null && r > lvl;
}

function iconHtml(e, size, which) {
  const cls = 'spr s' + (size || 44);
  const src = which === 'skill' && e.skillIcon ? e.skillIcon : e.icon;
  const ph = e.iconIsPlaceholder ? ' ph' : '';
  if (!src) return '';
  return '<span class="spr-wrap' + ph + '"><img class="' + cls + '" src="' + esc(src) +
    '" alt="" loading="lazy" onerror="poe2SprErr(this)" /></span>';
}
window.poe2SprErr = function (img) {
  img.style.visibility = 'hidden';
  const w = img.closest('.spr-wrap');
  if (w) w.classList.add('miss');
};

/* The chips every list row shows: what it costs you to use, and what kind of
   thing it is. Every one is read straight off a published field. */
function rowChips(gk, e) {
  const out = [];
  /* Announced but not in the game yet ({{unreleased}} on the source page). It
     leads because it changes what every other line on the row means - a reader
     must not be able to read a level or a location off a fight they cannot
     reach (re-verify 2026-09-03, R14). */
  if (e.unreleased) out.push('<span class="chip warn">Unreleased</span>');
  const r = reqLevelOf(e);
  if (r !== null) out.push('<span class="chip lvl">Lv ' + esc(r) + '</span>');
  const t = tierOf(e);
  if (t !== null) out.push('<span class="chip tier">Tier ' + esc(t) + '</span>');
  if ((gk === 'skillGems' || gk === 'supportGems') && e.primaryAttribute && e.primaryAttribute !== 'none') {
    const a = attrCls(e.primaryAttribute);
    out.push('<span class="chip' + (a ? ' ' + a : '') + '">' + esc(attrLabel(e.primaryAttribute).slice(0, 3)) + '</span>');
  }
  if (gk === 'currency' && typeof e.stackSize === 'number') {
    out.push('<span class="chip">Stacks ' + esc(e.stackSize) + '</span>');
  }
  return out.join('');
}

/* THE PRODUCT BAR. Three fixed sections, this order, these headings, on every
   entity in the app and in the vault wiki (NEW-GAME-TEMPLATE section 8). */
function beginnerHtml(e) {
  const b = e.beginner;
  if (!b || (!b.whatItIs && !b.whyItMatters && !b.whenToUseIt)) {
    return '<div class="beg-missing">The plain-language notes for this entry have not been written yet. ' +
      'What is below comes straight from the pull; the "what it is / why it matters / when to use it" ' +
      'lines are still owed for this group.</div>';
  }
  let h = '<div class="beg">';
  const rows = [['What it is', b.whatItIs], ['Why it matters', b.whyItMatters], ['When to use it', b.whenToUseIt]];
  for (const r of rows) {
    if (!r[1]) continue;
    h += '<p class="bh">' + esc(r[0]) + '</p><p class="bp">' + esc(r[1]) + '</p>';
  }
  h += '</div>';
  return h;
}

function linkChip(k, label) {
  if (!k) return '<span class="chip">' + esc(label) + '</span>';
  return '<button class="lchip" data-ent="' + esc(k) + '">' + esc(label) + '</button>';
}

function modListHtml(title, list, plain) {
  const c = cleanMods(list);
  if (!c.lines.length && !c.dropped) return '';
  let h = '<div class="sec-h">' + esc(title) + '</div>';
  if (c.lines.length) {
    h += '<ul class="mods' + (plain ? ' plain' : '') + '">' + c.lines.map(function (s) {
      return '<li>' + esc(s) + '</li>';
    }).join('') + '</ul>';
  }
  if (c.dropped) {
    h += '<div class="ph-note">' + c.dropped + (c.dropped === 1 ? ' line' : ' lines') +
      ' on this entry are stored as raw wiki markup in the current pull rather than as readable text, so they are not shown. ' +
      'The wiki link below has them in full.</div>';
  }
  return h;
}

function reqRowHtml(req) {
  if (!req) return '';
  const parts = [];
  for (const k of ['str', 'dex', 'int']) {
    if (typeof req[k] === 'number' && req[k] > 0) parts.push(req[k] + ' ' + ATTR_NAME[k]);
  }
  if (!parts.length) return '';
  return '<div class="st"><span class="k">Attribute requirement</span><span class="v">' + esc(parts.join(', ')) + '</span></div>';
}

function baseStatsHtml(bs) {
  if (!bs || typeof bs !== 'object') return '';
  let rows = '';
  for (const k of Object.keys(bs)) {
    const v = bs[k];
    if (typeof v !== 'number' || v === 0) continue;
    rows += '<div class="st"><span class="k">' + esc(labelOf(k)) + '</span><span class="v">' + esc(v) + '</span></div>';
  }
  if (!rows) return '';
  return '<div class="sec-h">Base item stats</div><div class="stats">' + rows + '</div>';
}

/*
 * THE CATALOGUE, SHOWN AS A CATALOGUE. Some uniques do not have fixed
 * modifiers - they roll N of them from a published pool, and the wiki stores
 * that pool inside the same field as the real mods. The dataset now keeps the
 * two apart (build_data.mjs extractRandomModifierPools), and this renders the
 * pool under its own heading so a reader is never told the item HAS 95
 * modifiers when it rolls 3 of 95.
 */
function randomPoolHtml(pools) {
  if (!Array.isArray(pools) || !pools.length) return '';
  let h = '';
  for (const p of pools) {
    if (!p || !Array.isArray(p.options) || !p.options.length) continue;
    h += '<div class="sec-h">' + esc(p.placeholder) + '</div>';
    h += '<div class="ph-note">The item does not grant all of these. It rolls from this list of ' +
      p.options.length + ', and which ones you get is decided when the item drops.</div>';
    h += '<ul class="mods plain">' + p.options.map(function (o) {
      return '<li>' + esc(o) + '</li>';
    }).join('') + '</ul>';
  }
  return h;
}

function statsHtml(e) {
  let rows = '';
  for (const key of Object.keys(e)) {
    if (SKIP.indexOf(key) !== -1) continue;
    const v = e[key];
    if (v === null || v === undefined || v === '') continue;
    if (Array.isArray(v) && !v.length) continue;
    if (typeof v === 'object' && !Array.isArray(v)) continue;
    const txt = fmtVal(key, v);
    if (!txt) continue;
    if (TPL_JUNK.test(txt)) continue;
    rows += '<div class="st"><span class="k">' + esc(labelOf(key)) + '</span><span class="v">' + esc(txt) + '</span></div>';
  }
  rows += reqRowHtml(e.requirements);
  if (!rows) return '';
  return '<div class="sec-h">Stats as pulled</div><div class="stats">' + rows + '</div>';
}

function attrsHtml(e) {
  const a = e.attributes;
  if (!a) return '';
  const pri = e.primaryAttributes || [];
  let h = '<div class="attrs">';
  for (const k of ['str', 'dex', 'int']) {
    if (typeof a[k] !== 'number') continue;
    h += '<div class="attr' + (pri.indexOf(k) !== -1 ? ' pri' : '') + '">' +
      '<span class="an">' + esc(ATTR_NAME[k]) + '</span><span class="av">' + esc(a[k]) + '</span></div>';
  }
  h += '</div>';
  return h;
}

/* ------------------------------------------------------------ detail sheet */

let sheetOpen = false;

function openEntity(k) {
  const e = ent(k);
  if (!e) return;
  const gk = groupOf(k);
  const nm = nameOf(e, gk);
  const body = $('#sheetBody');
  const sh = $('#sheet');
  if (!body || !sh) return;

  let h = '<button class="sheet-close" data-close>Close</button><div class="sheet-grab"></div>';
  const hero = iconHtml(e, 88);
  h += '<div class="sheet-hero">' + hero + '<div style="min-width:0">';
  h += '<h3>' + esc(nm) + '</h3>';
  const cat = catOf(gk, e);
  h += '<div class="ssub">' + esc(groupTitle(gk)) + (cat ? ' &middot; ' + esc(cat) : '') + '</div>';
  const chips = rowChips(gk, e);
  if (chips) h += '<div class="row wrap g6">' + chips + '</div>';
  h += '</div></div>';

  if (e.unreleased) {
    h += '<div class="ph-note">Announced, not released. The source page for this is tagged as unreleased, '
      + 'so it is not in the version of the game this app describes and there is no way to reach it yet.</div>';
  }
  if (e.skillsPartial && e.skillsPartialReason) {
    h += '<div class="ph-note">' + esc(e.skillsPartialReason) + '</div>';
  }
  if (e.iconIsPlaceholder) {
    h += '<div class="ph-note">' + esc(placeholderReason()) + '</div>';
  }
  if (e.stub === true) {
    h += '<div class="ph-note">The source page for this boss is barely started, so what is below is all the wiki publishes about it today.</div>';
  }

  h += beginnerHtml(e);

  if (Array.isArray(e.gemTags) && e.gemTags.length) {
    h += '<div class="row wrap g6 mt8">' + e.gemTags.map(function (t) {
      return '<span class="chip">' + esc(t) + '</span>';
    }).join('') + '</div>';
  }

  // Group-specific bodies. Everything here is a published field.
  if (gk === 'classes') {
    h += attrsHtml(e);
    if (Array.isArray(e.startingGear) && e.startingGear.length) {
      h += '<div class="sec-h">Starts with</div><div class="linkrow">' +
        e.startingGear.map(function (g) { return linkChip(resolveName(g), g); }).join('') + '</div>';
    }
    h += ascendancyHtml(e);
  }
  if (gk === 'skillGems' || gk === 'supportGems') {
    h += modListHtml('What the gem does', e.stats);
  }
  if (gk === 'uniques') {
    h += modListHtml('Implicit modifiers', e.implicitStats);
    h += modListHtml('Modifiers', e.explicitStats);
    h += randomPoolHtml(e.randomModifierPool);
    h += baseStatsHtml(e.baseStats);
    if (e.baseItem) {
      h += '<div class="sec-h">Built on</div><div class="linkrow">' + linkChip(resolveName(e.baseItem), e.baseItem) + '</div>';
    }
  }
  if (gk === 'currency') {
    h += modListHtml('What it does', e.effect);
  }
  if (gk === 'bosses') {
    h += modListHtml('Attacks it uses', e.skillNames, true);
    h += modListHtml('Fight modifiers', e.modifiers, true);
  }
  if (gk === 'glossary' && Array.isArray(e.seeAlso) && e.seeAlso.length) {
    h += '<div class="sec-h">See also</div><div class="linkrow">' +
      e.seeAlso.map(function (t) { return linkChip(resolveName(t), t); }).join('') + '</div>';
  }

  h += statsHtml(e);

  if (gk === 'skillGems' && e.skillIcon && e.skillIcon !== e.icon) {
    h += '<div class="sec-h">Skill icon</div><div class="row g8">' + iconHtml(e, 64, 'skill') +
      '<span class="small muted">The icon this skill shows on your action bar, as opposed to the gem in your inventory.</span></div>';
  }

  h += '<div class="actrow">';
  h += '<button class="tbtn' + (isPinned(k) ? ' on' : '') + '" data-pin="' + esc(k) + '">' +
    (isPinned(k) ? 'Pinned' : 'Pin to my plan') + '</button>';
  if (gk === 'classes') {
    const mine = myClass() === e.id;
    h += '<button class="tbtn' + (mine ? ' on' : '') + '" data-setclass="' + esc(e.id) + '">' +
      (mine ? 'This is my class' : 'Play as this') + '</button>';
  }
  h += '</div>';

  if (e.wiki) {
    h += '<div class="sec-h">Source</div><p class="srcbox">The facts on this page were read from ' +
      '<a href="' + esc(e.wiki) + '" target="_blank" rel="noopener noreferrer">' + esc(e.wiki) + '</a>. ' +
      'The plain-language sections above were written for this app.</p>';
  }

  body.innerHTML = h;
  body.scrollTop = 0;
  sh.hidden = false;
  sheetOpen = true;
  try { document.body.style.overflow = 'hidden'; } catch (err) { /* no-op */ }
  setHash('#/e/' + gk + '/' + e.id);
}

function placeholderReason() {
  const ci = (S.meta || {}).coreIcons || {};
  return ci.placeholderReason ||
    'The source hosts no artwork for this entry, so this is a stand-in drawn locally.';
}

/* Ascendancies are NESTED inside their parent class (the granularity decision
   locked for this game on 2026-09-01), so they are rendered here rather than
   as pages of their own. The dataset carries a name and a portrait for each
   and nothing more, and the card says so instead of implying more exists. */
function ascendancyHtml(e) {
  const list = e.ascendancies || [];
  if (!list.length) {
    return '<div class="sec-h">Ascendancies</div><div class="ph-note">' +
      (e.playable === false
        ? 'This class is not marked playable in the current pull and the dataset lists no ascendancies for it.'
        : 'The current pull lists no ascendancies for this class.') + '</div>';
  }
  let h = '<div class="sec-h">Ascendancies (' + list.length + ')</div>';
  for (const a of list) {
    h += '<div class="asc">' +
      '<span class="spr-wrap"><img class="spr s44" src="' + esc(a.icon || '') +
      '" alt="" loading="lazy" onerror="poe2SprErr(this)" /></span>' +
      '<span class="ab"><span class="an">' + esc(a.name) + '</span>' +
      (a.wiki ? '<span class="af"><a href="' + esc(a.wiki) + '" target="_blank" rel="noopener noreferrer">Read the full ascendancy on the wiki</a></span>' : '') +
      '</span></div>';
  }
  h += '<div class="ph-note">The pull carries a name and a portrait for each ascendancy and nothing else, ' +
    'so there are no plain-language notes for them yet. They are owed.</div>';
  return h;
}

function closeSheet() {
  const sh = $('#sheet');
  if (sh) sh.hidden = true;
  sheetOpen = false;
  try { document.body.style.overflow = ''; } catch (err) { /* no-op */ }
  setHash('#/' + S.view);
}

/* ------------------------------------------------------------------ search */

function buildIndex() {
  S.index = [];
  for (const d of S.gmeta) {
    const list = S.groups[d.key] || [];
    for (const e of list) {
      const nm = nameOf(e, d.key);
      const b = e.beginner || {};
      const hay = (nm + ' ' + catOf(d.key, e) + ' ' + (e.gemTags || []).join(' ') + ' ' +
        (e.itemClass || '') + ' ' + (e.baseItem || '') + ' ' +
        String(b.whatItIs || '').slice(0, 160)).toLowerCase();
      S.index.push({ k: keyOf(d.key, e.id), g: d.key, n: nm, hay: hay });
    }
  }
}

function searchRows(q, excludeTabs) {
  const s = q.toLowerCase().trim();
  if (!s) return [];
  const out = [];
  for (const r of S.index) {
    if (excludeTabs && excludeTabs.indexOf(TAB_OF[r.g] || 'more') !== -1) continue;
    if (r.hay.indexOf(s) === -1) continue;
    out.push(r);
    if (out.length >= 40) break;
  }
  out.sort(function (a, b) {
    const as = a.n.toLowerCase().indexOf(s), bs = b.n.toLowerCase().indexOf(s);
    const ar = as === 0 ? 0 : as > 0 ? 1 : 2, br = bs === 0 ? 0 : bs > 0 ? 1 : 2;
    return ar - br || a.n.localeCompare(b.n);
  });
  return out.slice(0, 30);
}

function searchHtml(placeholder) {
  return '<div class="search-wrap">' +
    '<span class="search-ic">&#128269;</span>' +
    '<input id="q" class="search" type="search" autocomplete="off" autocorrect="off" ' +
    'spellcheck="false" placeholder="' + esc(placeholder) + '" value="' + esc(S.q) + '" />' +
    (S.q ? '<button class="search-clear" data-clearq aria-label="Clear search">&#10005;</button>' : '') +
    '<div id="suggest"></div></div>';
}

/* The dropdown carries every entity the CURRENT tab cannot show, so the search
   field genuinely reaches all of them from all five tabs. */
function renderSuggest() {
  const box = $('#suggest');
  if (!box) return;
  if (!S.q.trim()) { box.innerHTML = ''; box.className = ''; return; }
  const inline = ['classes', 'items', 'more'];
  const exclude = inline.indexOf(S.view) !== -1 ? [S.view] : [];
  const rows = searchRows(S.q, exclude);
  if (!rows.length) {
    if (exclude.length) { box.innerHTML = ''; box.className = ''; return; }
    box.className = 'suggest';
    box.innerHTML = '<div class="sug-empty">Nothing matches "' + esc(S.q) + '".</div>';
    return;
  }
  box.className = 'suggest';
  box.innerHTML = rows.map(function (r) {
    return '<button class="sug-row" data-ent="' + esc(r.k) + '">' +
      '<span class="nm">' + esc(r.n) + '</span>' +
      '<span class="tg">' + esc(groupTitle(r.g)) + '</span></button>';
  }).join('');
}

/* -------------------------------------------------------------- views: Start */

function renderStart() {
  let h = '<div class="view">';
  h += searchHtml('Search everything in Path of Exile 2');

  h += '<h2 class="vh">Your first 10 minutes</h2>';
  h += '<p class="lead">These are the words the game throws at you in your first hour, in the order you meet them. ' +
    'Tap any step for the full explanation.</p>';
  h += '<ol class="steps">';
  let steps = 0;
  for (const k of START_STEPS) {
    const e = ent(k);
    if (!e) continue;
    steps++;
    const gk = groupOf(k);
    const b = e.beginner || {};
    const line = firstSentences(b.whatItIs, 2);
    h += '<li><button class="sl" data-ent="' + esc(k) + '">' + esc(nameOf(e, gk)) + '</button>' +
      '<div class="sd">' + esc(line) +
      ' <button class="more" data-ent="' + esc(k) + '">More</button></div></li>';
  }
  h += '</ol>';
  if (!steps) {
    h += '<div class="card muted">The walkthrough steps are not in this dataset. Use the glossary on the More tab.</div>';
  }

  /* PICK YOUR FIRST CLASS - derived, never curated. A class qualifies when the
     data marks it playable AND it leans on a SINGLE primary attribute, which
     is the set where there is one number to raise instead of two. If a later
     pull changes a class's attributes or its playable flag it leaves this list
     on its own, with no edit here. */
  const first = (S.groups.classes || []).filter(function (c) {
    return c.playable !== false && (c.primaryAttributes || []).length === 1;
  }).sort(function (a, b) { return String(a.name).localeCompare(String(b.name)); });
  if (first.length) {
    h += '<h2 class="vh">Pick your first class</h2>';
    h += '<p class="lead">The playable classes that lean on a single attribute, so there is one number to raise ' +
      'instead of two. Any of them will finish the campaign; this is about how much you have to juggle while you learn.</p>';
    for (const c of first) {
      const b = c.beginner || {};
      const pa = (c.primaryAttributes || [])[0] || '';
      h += '<button class="rowcard" data-ent="' + esc(keyOf('classes', c.id)) + '">' +
        iconHtml(c, 44) +
        '<span class="rb"><span class="rn">' + esc(c.name) + '</span>' +
        '<span class="rm">' + esc(firstSentences(b.whyItMatters, 1) || firstSentences(b.whatItIs, 1)) + '</span></span>' +
        '<span class="rc"><span class="chip ' + esc(attrCls(pa)) + '">' +
        esc(ATTR_NAME[pa] || '') + '</span></span></button>';
    }
    h += '<div class="row g8 mt8 mb10"><button class="tbtn" data-goto="classes">See all ' +
      (S.groups.classes || []).length + ' classes</button></div>';
  }

  const gl = S.groups.glossary || [];
  if (gl.length) {
    h += '<h2 class="vh">Words you will hear</h2>';
    h += '<p class="lead">' + gl.length + ' terms in plain English. Search above for any of them, ' +
      'or open the full list on More.</p>';
    h += '<div class="row wrap g6">' + gl.slice(0, 16).map(function (t) {
      return '<button class="lchip" data-ent="' + esc(keyOf('glossary', t.id)) + '">' + esc(t.term) + '</button>';
    }).join('') + '</div>';
    h += '<div class="row g8 mt8"><button class="tbtn" data-goto="more">Open the full glossary</button></div>';
  }

  h += gapCardHtml();
  h += freshBlockHtml();
  h += '</div>';
  return h;
}

/* ------------------------------------------------------------ views: Classes */

function classPasses(c, scoped) {
  if (scoped && S.cAttr !== 'all' && (c.primaryAttributes || []).indexOf(S.cAttr) === -1) return false;
  if (S.cPlayable && c.playable === false) return false;
  const q = S.q.toLowerCase().trim();
  if (!q) return true;
  const b = c.beginner || {};
  return (c.name + ' ' + catOf('classes', c) + ' ' + (c.weaponFocus || '') + ' ' +
    (c.ascendancies || []).map(function (a) { return a.name; }).join(' ') + ' ' +
    String(b.whatItIs || '')).toLowerCase().indexOf(q) !== -1;
}

function classAttrCount(a) {
  let n = 0;
  for (const c of (S.groups.classes || [])) {
    if (a !== 'all' && (c.primaryAttributes || []).indexOf(a) === -1) continue;
    if (classPasses(c, false)) n++;
  }
  return n;
}

function classChipsHtml() {
  const attrs = ['all', 'str', 'dex', 'int'];
  let h = '<div class="chiprow">' + attrs.map(function (a) {
    return '<button class="fbtn' + (S.cAttr === a ? ' on' : '') + '" data-cattr="' + esc(a) + '">' +
      esc((a === 'all' ? 'All' : ATTR_NAME[a]) + ' ' + classAttrCount(a)) + '</button>';
  }).join('') + '</div>';
  h += '<div class="row g8 mb10"><button class="tbtn' + (S.cPlayable ? ' on' : '') +
    '" data-cplayable>Only classes marked playable</button></div>';
  return h;
}

/* The lead sentence counts the roster from the data, never from a word typed
   into the prose. It used to open "Twelve classes" directly above a chip row
   that computes "All 12" from data/classes.json - two statements of one fact,
   one of which cannot follow a patch. Early Access has already added classes
   mid-0.x (Druid, Huntress), so the spelled-out version was one pull away from
   contradicting the chip beside it. */
function renderClasses() {
  const nClasses = (S.groups.classes || []).length;
  let h = '<div class="view">';
  h += searchHtml('Search classes, gems, items, bosses...');
  h += '<p class="lead">All ' + nClasses + ' classes, and the ascendancies each one can specialise into. ' +
    'Tap a class for what it does, what it starts with and how its ascendancies differ.</p>';
  h += '<div id="chipRegion">' + classChipsHtml() + '</div>';
  h += '<div id="listRegion"></div>';
  h += '</div>';
  return h;
}

function classList() {
  return (S.groups.classes || []).filter(function (c) { return classPasses(c, true); });
}

function fillClasses() {
  const box = $('#listRegion');
  if (!box) return;
  const list = classList();
  if (!list.length) {
    box.innerHTML = '<div class="card muted">No class matches that. The dropdown above searches every other tab.</div>';
    return;
  }
  box.innerHTML = '<div class="grid">' + list.map(function (c) {
    const asc = (c.ascendancies || []).length;
    return '<button class="gcard" data-ent="' + esc(keyOf('classes', c.id)) + '">' +
      '<span class="gi">' + iconHtml(c, 64) + '</span>' +
      '<span class="gn">' + esc(c.name) + '</span>' +
      '<span class="gm">' + esc(catOf('classes', c)) +
      (asc ? ' &middot; ' + asc + (asc === 1 ? ' ascendancy' : ' ascendancies') : '') + '</span>' +
      '<span class="gc">' + (c.unreleased
        ? '<span class="chip warn">Unreleased</span>'
        : c.playable === false
          ? '<span class="chip warn">Not marked playable</span>'
          : (myClass() === c.id ? '<span class="chip lvl">My class</span>' : '')) + '</span></button>';
  }).join('') + '</div>';
}

/* -------------------------------------------------------------- views: Items */

function itemGroups() {
  const known = ITEM_ORDER.filter(function (g) { return (S.groups[g] || []).length; });
  const extra = S.gmeta.filter(function (d) {
    return TAB_OF[d.key] === 'items' && ITEM_ORDER.indexOf(d.key) === -1 && (S.groups[d.key] || []).length;
  }).map(function (d) { return d.key; });
  return known.concat(extra);
}

function distinctCats(gk) {
  const seen = [];
  for (const e of (S.groups[gk] || [])) {
    const v = catOf(gk, e);
    if (v && seen.indexOf(v) === -1) seen.push(v);
  }
  return seen.sort(function (a, b) { return a.localeCompare(b); });
}
function distinctTiers(gk) {
  const seen = [];
  for (const e of (S.groups[gk] || [])) {
    const t = tierOf(e);
    if (t !== null && seen.indexOf(t) === -1) seen.push(t);
  }
  return seen.sort(function (a, b) { return a - b; });
}

function itemHay(gk, e) {
  const b = e.beginner || {};
  return (nameOf(e, gk) + ' ' + catOf(gk, e) + ' ' + (e.gemTags || []).join(' ') + ' ' +
    (e.baseItem || '') + ' ' + String(b.whatItIs || '')).toLowerCase();
}

/* THE ONE PREDICATE THE ITEMS TAB FILTERS ON. The list, its pager and the count
   printed on every group chip all go through this, so a chip can no longer
   state a number the list under it disagrees with. Round 2 caught exactly that:
   with the level filter on, the chips printed the raw dataset lengths
   (All 1630 / 368 / 550 / 451 / 261) while the pager truthfully said
   "60 of 1172" - two counts for the same visible set, 458 apart, with the
   active filter chip sitting between them.

   `scoped` says whether the group/category/tier SELECTION applies:
     - true for the list itself whenever a single group is selected;
     - true for the chip of the group ALREADY selected, because that chip is
       describing what is on screen right now;
     - false for every other chip and for All, because tapping one of those
       resets iCat and iTier (see the data-igroup handler), so its number has to
       be what you would get AFTER the tap.
   The level filter and the search box are never scoped away: they survive every
   chip tap, so they narrow every count. */
function itemPasses(gk, e, scoped) {
  if (scoped && S.iCat !== 'all' && catOf(gk, e) !== S.iCat) return false;
  if (scoped && S.iTier !== 'all' && String(tierOf(e)) !== String(S.iTier)) return false;
  if (S.onlyUsable && gatedAbove(e, myLevel())) return false;
  const q = S.q.toLowerCase().trim();
  if (q && itemHay(gk, e).indexOf(q) === -1) return false;
  return true;
}

function itemGroupCount(gk, scoped) {
  let n = 0;
  for (const e of (S.groups[gk] || [])) if (itemPasses(gk, e, scoped)) n++;
  return n;
}

/* The unfiltered dataset size. It exists in exactly one place, with a name that
   says what it is, and it is used for exactly one sentence: "N of M entries are
   hidden right now". It is never a chip count - that is the whole finding. */
function itemDatasetTotal(gs) {
  let n = 0;
  for (const g of gs) n += (S.groups[g] || []).length;
  return n;
}

function itemChipsHtml() {
  const gs = itemGroups();
  const counts = {};
  let total = 0;
  for (const g of gs) { counts[g] = itemGroupCount(g, false); total += counts[g]; }
  if (S.iGroup !== 'all' && Object.prototype.hasOwnProperty.call(counts, S.iGroup)) {
    counts[S.iGroup] = itemGroupCount(S.iGroup, true);
  }
  let h = '';
  h += '<div class="chiprow">' +
    '<button class="fbtn' + (S.iGroup === 'all' ? ' on' : '') + '" data-igroup="all">All ' + total + '</button>' +
    gs.map(function (g) {
      return '<button class="fbtn' + (S.iGroup === g ? ' on' : '') + '" data-igroup="' + esc(g) + '">' +
        esc(groupTitle(g)) + ' ' + counts[g] + '</button>';
    }).join('') + '</div>';

  if (S.iGroup !== 'all') {
    const cats = distinctCats(S.iGroup);
    if (cats.length > 1) {
      h += '<div class="chiprow">' + ['all'].concat(cats).map(function (c) {
        return '<button class="fbtn' + (S.iCat === c ? ' on' : '') + '" data-icat="' + esc(c) + '">' +
          esc(c === 'all' ? 'Every category' : c) + '</button>';
      }).join('') + '</div>';
    }
    const tiers = distinctTiers(S.iGroup);
    if (tiers.length > 1) {
      h += '<div class="chiprow">' + ['all'].concat(tiers).map(function (t) {
        return '<button class="fbtn' + (String(S.iTier) === String(t) ? ' on' : '') + '" data-itier="' + esc(t) + '">' +
          esc(t === 'all' ? 'Every tier' : 'Tier ' + t) + '</button>';
      }).join('') + '</div>';
    }
  }

  h += '<div class="row g8 mb10"><button class="tbtn' + (S.onlyUsable ? ' on' : '') +
    '" data-usable>Hide what level ' + myLevel() + ' cannot use yet</button></div>';

  /* Say out loud that the chip counts moved, and by how much. A filtered count
     that silently replaces an unfiltered one is the same lie in the other
     direction. Both numbers are derived; neither is written down anywhere. */
  if (S.onlyUsable || S.q.trim()) {
    const raw = itemDatasetTotal(gs);
    if (raw > total) {
      h += '<p class="small muted mb10">The counts above are what these filters leave: ' +
        (raw - total) + ' of ' + raw + ' entries are hidden right now.</p>';
    }
  }
  return h;
}

function renderItems() {
  let h = '<div class="view">';
  h += searchHtml('Search gems, uniques, currency...');
  h += '<p class="lead">Everything you can hold: the skill gems you cast with, the supports that change them, ' +
    'the unique items worth building around, and the currency that changes your gear.</p>';
  h += '<div id="chipRegion">' + itemChipsHtml() + '</div>';
  h += '<div id="listRegion"></div>';
  h += '</div>';
  return h;
}

function itemRows() {
  const gs = S.iGroup === 'all' ? itemGroups() : [S.iGroup];
  const scoped = S.iGroup !== 'all';
  const out = [];
  for (const g of gs) {
    for (const e of (S.groups[g] || [])) {
      if (!itemPasses(g, e, scoped)) continue;
      out.push({ g: g, e: e });
    }
  }
  const order = itemGroups();
  out.sort(function (a, b) {
    if (a.g !== b.g) return order.indexOf(a.g) - order.indexOf(b.g);
    const ac = catOf(a.g, a.e), bc = catOf(b.g, b.e);
    if (ac !== bc) return ac.localeCompare(bc);
    return String(nameOf(a.e, a.g)).localeCompare(String(nameOf(b.e, b.g)));
  });
  return out;
}

function fillItems() {
  const box = $('#listRegion');
  if (!box) return;
  const rows = itemRows();
  if (!rows.length) {
    box.innerHTML = '<div class="card muted">Nothing here matches. The dropdown above searches every other tab.</div>';
    return;
  }
  const shown = rows.slice(0, S.limit);
  let h = '';
  let head = '';
  for (const r of shown) {
    const label = S.iGroup === 'all' ? groupTitle(r.g) : (catOf(r.g, r.e) || groupTitle(r.g));
    if (label !== head) { head = label; h += '<h3 class="sh">' + esc(head) + '</h3>'; }
    const b = r.e.beginner || {};
    h += '<button class="rowcard" data-ent="' + esc(keyOf(r.g, r.e.id)) + '">' +
      iconHtml(r.e, 44) +
      '<span class="rb"><span class="rn">' + esc(nameOf(r.e, r.g)) + '</span>' +
      '<span class="rm">' + esc(firstSentences(b.whatItIs, 1)) + '</span></span>' +
      '<span class="rc">' + rowChips(r.g, r.e) + '</span></button>';
  }
  if (rows.length > shown.length) {
    h += '<button class="morebtn" data-more>Show ' +
      Math.min(PAGE_SIZE, rows.length - shown.length) + ' more (' + shown.length + ' of ' + rows.length + ')</button>';
  }
  box.innerHTML = h;
}

/* ------------------------------------------------------------- views: Builds */

function renderBuilds() {
  /* THE ONLY SEAM between this file and a future Builds lane. A later phase
     ships js/builds.js, registers window.POE2_BUILDS with a render() that
     returns HTML, adds its <script> to index.html and its path to the registry
     `scripts` list. Everything below is what runs until then, and what runs if
     that file is ever missing or throws - the app must not lose a tab over one
     script. See README.md, checklist line 6. */
  if (window.POE2_BUILDS && typeof window.POE2_BUILDS.render === 'function') {
    try { return window.POE2_BUILDS.render(); } catch (e) { /* fall through */ }
  }

  const m = S.meta || {};
  let h = '<div class="view">';
  h += searchHtml('Search anything while you plan');

  h += '<h2 class="vh">Build planner</h2>';

  /* FRESHNESS ON THIS TAB SPECIFICALLY (NEW-GAME-TEMPLATE section 8): a build
     recommendation without a date is a claim with no expiry, so the pull date
     AND the patch the data reflects are rendered here, not only on More. */
  h += '<div class="card"><div class="fresh">' +
    '<span>Data pulled <b>' + esc(prettyDate(m.pulledAt)) + '</b></span><span class="faint">&middot;</span>' +
    '<span>Reflects patch <b>' + esc(m.pulledAtVersion || 'unknown') + '</b></span></div>' +
    '<p class="small muted" style="margin:8px 0 0">Path of Exile 2 is in Early Access and patches land every one to three weeks. ' +
    'Anything on this tab describes the patch named above and nothing later.</p></div>';

  h += '<div class="ruling">Nothing on this tab is generated or scored yet. It holds your character, ' +
    'the gems and items you have pinned, and the level filter that the other tabs read. ' +
    'When a generator lands it will print a reason under every pick, and it will still be the best option ' +
    'it found in the data above rather than a proof that nothing better exists.</div>';

  h += '<h3 class="sh">Your character</h3>';
  h += '<div class="card">';
  h += '<div class="lvlctl"><label for="lvl" class="small muted">Character level</label>' +
    '<input id="lvl" type="number" min="1" max="100" inputmode="numeric" value="' + esc(myLevel()) + '" />' +
    '<span class="small faint">Filters every list to what you can actually equip.</span></div>';

  const cls = (S.groups.classes || []).filter(function (c) { return c.playable !== false; });
  if (cls.length) {
    h += '<div class="lvlctl" style="margin-top:12px"><label for="clsSel" class="small muted">Class</label>' +
      '<select id="clsSel" class="profsel"><option value="">Not chosen</option>' +
      cls.map(function (c) {
        return '<option value="' + esc(c.id) + '"' + (myClass() === c.id ? ' selected' : '') + '>' + esc(c.name) + '</option>';
      }).join('') + '</select></div>';
    const mine = (S.groups.classes || []).filter(function (c) { return c.id === myClass(); })[0];
    if (mine) {
      h += '<div class="row g8 mt8"><button class="tbtn" data-ent="' + esc(keyOf('classes', mine.id)) +
        '">Open ' + esc(mine.name) + '</button></div>';
    }
  }

  h += '<div class="lvlctl" style="margin-top:12px"><label for="prof" class="small muted">Saved plan</label>' +
    '<select id="prof" class="profsel">' + Object.keys(ST.profiles).map(function (id) {
      return '<option value="' + esc(id) + '"' + (id === ST.active ? ' selected' : '') + '>' + esc(ST.profiles[id].name) + '</option>';
    }).join('') + '</select>' +
    '<button class="tbtn" data-newprof>New</button>' +
    '<button class="tbtn" data-renprof>Rename</button>' +
    (Object.keys(ST.profiles).length > 1 ? '<button class="tbtn danger" data-delprof>Delete</button>' : '') +
    '</div>';
  h += '</div>';

  const pinKeys = prof().pins.filter(function (k) { return !!ent(k); });
  h += '<h3 class="sh">Pinned (' + pinKeys.length + ')</h3>';
  if (!pinKeys.length) {
    h += '<div class="card muted small">Nothing pinned yet. Open any gem, unique or currency item and tap ' +
      '"Pin to my plan" to park it here while you work out a build.</div>';
  } else {
    let maxLvl = 0, counted = 0;
    for (const k of pinKeys) {
      const r = reqLevelOf(ent(k));
      if (r !== null) { counted++; if (r > maxLvl) maxLvl = r; }
    }
    if (counted) {
      h += '<div class="card tight"><div class="fresh">' +
        '<span>Highest level requirement <b>' + esc(maxLvl) + '</b></span><span class="faint">&middot;</span>' +
        '<span>' + counted + ' of ' + pinKeys.length + ' publish one</span></div>' +
        '<p class="small faint" style="margin:6px 0 0">The level this plan is fully usable at, taken from the ' +
        'entries that publish a required level. Entries with none are not counted.</p></div>';
    }
    for (const k of pinKeys) {
      const e = ent(k);
      const gk = groupOf(k);
      h += '<button class="rowcard" data-ent="' + esc(k) + '">' + iconHtml(e, 44) +
        '<span class="rb"><span class="rn">' + esc(nameOf(e, gk)) + '</span>' +
        '<span class="rm">' + esc(groupTitle(gk)) + ' &middot; ' + esc(catOf(gk, e)) + '</span></span>' +
        '<span class="rc">' + rowChips(gk, e) + '</span></button>';
    }
  }

  // Forward-compatible: curated starter builds ship as data or not at all.
  if (Array.isArray(S.groups.builds) && S.groups.builds.length) {
    h += '<h3 class="sh">Starter builds</h3>';
    for (const b of S.groups.builds) {
      h += '<button class="rowcard" data-ent="' + esc(keyOf('builds', b.id)) + '">' + iconHtml(b, 44) +
        '<span class="rb"><span class="rn">' + esc(nameOf(b, 'builds')) + '</span>' +
        '<span class="rm">' + esc(firstSentences((b.beginner || {}).whatItIs, 1)) + '</span></span></button>';
    }
  } else {
    h += '<h3 class="sh">Starter builds</h3>';
    h += '<div class="mount-slot">No curated starter builds are in this dataset yet. ' +
      'When they land they appear here, and every gem and item they name will be one you can open from this list.</div>';
  }

  h += '</div>';
  return h;
}

/* --------------------------------------------------------------- views: More */

function moreSections() {
  const out = [];
  for (const gk of MORE_ORDER) if ((S.groups[gk] || []).length) out.push(gk);
  for (const d of S.gmeta) {
    if ((TAB_OF[d.key] || 'more') !== 'more') continue;
    if (out.indexOf(d.key) !== -1) continue;
    if ((S.groups[d.key] || []).length) out.push(d.key);
  }
  out.push('about');
  return out;
}

function moreHay(gk, e) {
  const b = e.beginner || {};
  return (nameOf(e, gk) + ' ' + catOf(gk, e) + ' ' + (e.locations || []).join(' ') + ' ' +
    String(b.whatItIs || '')).toLowerCase();
}

/* The More tab's half of the same contract. With a query typed the section chip
   must not narrow anything (the search field reaches every entity from every
   tab), so the query short-circuits the boss-location filter. `scoped` is true
   for the section actually being listed and for its own chip; false for the
   other chips, because tapping one of those resets mCat (see data-msec). */
function morePasses(gk, e, scoped) {
  const q = S.q.toLowerCase().trim();
  if (q) return moreHay(gk, e).indexOf(q) !== -1;
  if (scoped && gk === 'bosses' && S.mCat !== 'all' && catOf(gk, e) !== S.mCat) return false;
  return true;
}

function moreGroupCount(gk, scoped) {
  let n = 0;
  for (const e of (S.groups[gk] || [])) if (morePasses(gk, e, scoped)) n++;
  return n;
}

function moreChipsHtml() {
  const secs = moreSections();
  let h = '<div class="chiprow">' + secs.map(function (g) {
    const label = g === 'about'
      ? 'About the data'
      : groupTitle(g) + ' ' + moreGroupCount(g, g === S.mSec);
    return '<button class="fbtn' + (S.mSec === g ? ' on' : '') + '" data-msec="' + esc(g) + '">' +
      esc(label) + '</button>';
  }).join('') + '</div>';

  if (S.mSec === 'bosses') {
    const cats = distinctCats('bosses');
    h += '<div class="chiprow">' + ['all'].concat(cats).map(function (c) {
      return '<button class="fbtn' + (S.mCat === c ? ' on' : '') + '" data-mcat="' + esc(c) + '">' +
        esc(c === 'all' ? 'Everywhere' : c) + '</button>';
    }).join('') + '</div>';
  }
  return h;
}

function renderMore() {
  const secs = moreSections();
  if (secs.indexOf(S.mSec) === -1) S.mSec = secs[0];
  let h = '<div class="view">';
  h += searchHtml('Search everything in Path of Exile 2');
  h += '<div id="chipRegion">' + moreChipsHtml() + '</div>';
  h += '<div id="listRegion"></div>';
  h += '</div>';
  return h;
}

function fillMore() {
  const box = $('#listRegion');
  if (!box) return;
  const q = S.q.toLowerCase().trim();

  if (!q && S.mSec === 'about') { box.innerHTML = aboutHtml(); return; }

  /* With a query typed, More searches BOTH of its groups rather than only the
     section chip that happens to be selected - the search field is supposed to
     reach every entity from every tab, and a section chip must not narrow it. */
  const groups = q
    ? moreSections().filter(function (g) { return g !== 'about'; })
    : [S.mSec];

  let rows = [];
  for (const g of groups) {
    for (const e of (S.groups[g] || [])) {
      if (!morePasses(g, e, true)) continue;
      rows.push({ g: g, e: e });
    }
  }
  if (!rows.length) {
    box.innerHTML = '<div class="card muted">Nothing here matches. The dropdown above searches every other tab.</div>';
    return;
  }

  // The glossary is a chip cloud rather than a row list: 55 short terms.
  if (!q && S.mSec === 'glossary') {
    box.innerHTML = '<p class="lead">Every word a newcomer meets in the first hour, in plain English.</p>' +
      '<div class="row wrap g6">' + rows.map(function (r) {
        return '<button class="lchip" data-ent="' + esc(keyOf(r.g, r.e.id)) + '">' +
          esc(nameOf(r.e, r.g)) + '</button>';
      }).join('') + '</div>';
    return;
  }

  rows.sort(function (a, b) {
    if (a.g !== b.g) return String(a.g).localeCompare(String(b.g));
    const ac = catOf(a.g, a.e), bc = catOf(b.g, b.e);
    if (ac !== bc) return ac.localeCompare(bc);
    return String(nameOf(a.e, a.g)).localeCompare(String(nameOf(b.e, b.g)));
  });
  const shown = rows.slice(0, S.limit);
  let h = '';
  let head = '';
  for (const r of shown) {
    const label = esc(groupTitle(r.g)) + (r.g === 'bosses' ? ' &middot; ' + esc(catOf(r.g, r.e)) : '');
    if (label !== head) { head = label; h += '<h3 class="sh">' + head + '</h3>'; }
    const b = r.e.beginner || {};
    h += '<button class="rowcard" data-ent="' + esc(keyOf(r.g, r.e.id)) + '">' +
      iconHtml(r.e, 44) +
      '<span class="rb"><span class="rn">' + esc(nameOf(r.e, r.g)) + '</span>' +
      '<span class="rm">' + esc(firstSentences(b.whatItIs, 1)) + '</span></span></button>';
  }
  if (rows.length > shown.length) {
    h += '<button class="morebtn" data-more>Show ' +
      Math.min(PAGE_SIZE, rows.length - shown.length) + ' more (' + shown.length + ' of ' + rows.length + ')</button>';
  }
  box.innerHTML = h;
}

function aboutHtml() {
  const m = S.meta || {};
  let h = '<h3 class="sh">Where this comes from</h3><div class="card srcbox">';
  if (Array.isArray(m.sources)) {
    for (const s of m.sources) {
      h += '<p style="margin:0 0 8px"><b>' + esc(s.name) + '</b> &middot; ' + esc(s.use) +
        (s.licence ? ' &middot; ' + esc(s.licence) : '') + '<br />' +
        '<a href="' + esc(s.url) + '" target="_blank" rel="noopener noreferrer">' + esc(s.url) + '</a></p>';
    }
  }
  h += '<p style="margin:8px 0 0">The numbers and modifier lines come from that source as data. ' +
    'Every "what it is / why it matters / when to use it" section was written for this app, not copied.</p>';
  h += '</div>';
  h += gapCardHtml();
  h += freshBlockHtml();
  return h;
}

/* ----------------------------------------------------------------- shared */

function totalEntities() {
  let n = 0;
  for (const d of S.gmeta) n += (S.groups[d.key] || []).length;
  return n;
}

function freshBlockHtml() {
  const m = S.meta || {};
  return '<h3 class="sh">Freshness</h3><div class="card"><div class="fresh">' +
    '<span>Pulled <b>' + esc(prettyDate(m.pulledAt)) + '</b></span><span class="faint">&middot;</span>' +
    '<span>Reflects patch <b>' + esc(m.pulledAtVersion || 'unknown') + '</b></span><span class="faint">&middot;</span>' +
    '<span><b>' + totalEntities() + '</b> entries</span></div>' +
    '<p class="small muted" style="margin:8px 0 0">' + esc(m.scope || '') + '</p></div>';
}

/* THE HONESTY SURFACE. Every count on every tab is a snapshot of one Early
   Access patch, and parts of the source are thin: some bosses have no infobox,
   some entries have no artwork. All of it is DERIVED from data/meta.json -
   there is no hardcoded number anywhere in this file. */
function gapCardHtml() {
  const m = S.meta || {};
  const ci = m.coreIcons || {};
  const sg = m.sourceGaps || {};
  let h = '<h3 class="sh">What is missing from this data</h3><div class="card">';
  h += '<p style="margin:0">This is one snapshot of an Early Access game. Every count you see is what patch ' +
    esc(m.pulledAtVersion || 'this pull') + ' published on ' + esc(prettyDate(m.pulledAt)) +
    ', not a final roster, and Grinding Gear Games patch every one to three weeks.</p>';
  if (m.scope) h += '<p class="small muted" style="margin:8px 0 0">' + esc(m.scope) + '</p>';
  /* NOUNS ARE PART OF THE NUMBER. This paragraph counts ICONS: meta.coreIcons
     covers the 1810 entities that can carry artwork, and the glossary has none.
     The Freshness line eight lines below it counts ENTRIES: every entity plus
     the 55 glossary terms, 1865. Both are correct and they will never be equal,
     so they must never share a noun - shipping "101 of 1810 entries" above
     "1865 entries" in one panel read as a contradiction (round-3 finding).
     assert-poe2-ui A6 fails the build if the two nouns collide again. */
  if (typeof ci.placeholders === 'number' && ci.placeholders && typeof ci.total === 'number') {
    h += '<p class="small muted" style="margin:8px 0 0">' + ci.placeholders + ' of ' + ci.total +
      ' entity icons show a plain stand-in instead of artwork. ' + esc(placeholderReason()) + '</p>';
  }
  if (typeof sg.bossPagesWithoutInfobox === 'number' && sg.bossPagesWithoutInfobox) {
    h += '<p class="small muted" style="margin:8px 0 0">' + sg.bossPagesWithoutInfobox +
      ' boss pages carry no stat box on the source wiki, so those fights list a location and little else.</p>';
  }
  h += '</div>';
  return h;
}

function renderStageBanner() {
  const el = $('#stagebar');
  if (!el) return;
  const m = S.meta || {};
  const txt = 'Early Access data: this app describes patch ' + (m.pulledAtVersion || 'unknown') +
    ', pulled ' + prettyDate(m.pulledAt) + '. Counts and numbers change with every patch.';
  el.innerHTML = '<div class="pb"><span class="pbi">&#9888;</span><span>' + esc(txt) + '</span></div>';
}

/* --------------------------------------------------------------- rendering */

const VIEWS = {
  start: renderStart, classes: renderClasses, items: renderItems,
  builds: renderBuilds, more: renderMore
};

function render() {
  const a = app();
  if (!a) return;
  const fn = VIEWS[S.view] || renderStart;
  a.innerHTML = fn();
  if (S.view === 'classes') fillClasses();
  if (S.view === 'items') fillItems();
  if (S.view === 'more') fillMore();
  renderSuggest();
  const tabs = document.querySelectorAll('#tabbar .tab');
  for (let i = 0; i < tabs.length; i++) {
    tabs[i].classList.toggle('on', tabs[i].getAttribute('data-view') === S.view);
  }
}

/* THE CHIP ROW IS PART OF THE LIST, NOT PART OF THE PAGE. Every chip on the
   three list tabs now carries a count derived from the same predicate the list
   filters on. That makes the chips as query-sensitive as the rows - so the
   search box, which refills the list WITHOUT a full render() so the field it is
   being typed into survives, has to refill the chips too. Caught in the browser
   on the first cut of this fix: with "fire" typed, the Unique Items chip still
   read 8 above a single visible row. Both regions, or neither. */
function fillChips() {
  const box = $('#chipRegion');
  if (!box) return;
  if (S.view === 'classes') box.innerHTML = classChipsHtml();
  else if (S.view === 'items') box.innerHTML = itemChipsHtml();
  else if (S.view === 'more') box.innerHTML = moreChipsHtml();
}

function refillList() {
  if (S.view === 'classes') { fillChips(); return fillClasses(); }
  if (S.view === 'items') { fillChips(); return fillItems(); }
  if (S.view === 'more') { fillChips(); return fillMore(); }
}

/* CHARACTER LEVEL -> REDRAW. Every other control that writes to the profile
   redraws on the spot: the class select is `setMyClass(t.value); render();` and
   the plan select is `saveState(); render();`. The level field was the one write
   with no redraw behind it, and it is the field the whole Builds tab gates on -
   so the card kept printing "It is fully assembled at level 12, and you are
   level 1." after the input said 40, and only a tab bounce corrected it. Worse,
   typing 40 into a field already holding 12 gave 1240 in the input, 100 in
   storage (clamped) and "level 12" on screen: three numbers for one fact.

   It could not simply call render(), because a render() per keystroke rebuilds
   #app and destroys the input being typed into. So the WRITE stays immediate
   (storage is never behind the field) and only the REDRAW is debounced; the
   redraw then re-asserts the field from myLevel() so the 1-100 clamp is visible
   rather than hidden, and puts the caret back. `change` (blur / Enter) flushes
   it at once, which is also what re-fills a field the player emptied. */
const LVL_REDRAW_MS = 350;
let lvlTimer = null;
let lvlRedrawing = false;

function syncLevelInput() {
  const el = $('#lvl');
  if (!el) return;
  const want = String(myLevel());
  if (el.value !== want) el.value = want;
}

function flushLevelRedraw() {
  /* RE-ENTRANCY IS NOT THEORETICAL HERE - it was caught in the browser on the
     first cut of this fix, as an uncaught NotFoundError: "Failed to set the
     'innerHTML' property... The node to be removed is no longer a child of this
     node. Perhaps it was moved in a 'blur' event handler?". Chrome dispatches
     blur AND change from INSIDE the innerHTML assignment that removes a focused
     input; the change handler below redraws, so the inner redraw replaced #app's
     children and then the outer assignment failed on nodes that were already
     gone. The redraw died half-done and the field lost focus, eating the next
     keystroke. Both halves of the fix are load-bearing: this flag swallows the
     nested call, and the blur below moves that dispatch to a moment when the
     DOM is not mid-write. */
  if (lvlRedrawing) return;
  if (lvlTimer) { clearTimeout(lvlTimer); lvlTimer = null; }
  lvlRedrawing = true;
  try {
    const el0 = $('#lvl');
    const refocus = !!(el0 && document.activeElement === el0);
    if (refocus) { try { el0.blur(); } catch (e) { /* no-op */ } }
    render();
    syncLevelInput();
    if (!refocus) return;
    const el = $('#lvl');
    if (!el) return;
    try { el.focus(); } catch (e) { /* no-op */ }
    /* setSelectionRange throws InvalidStateError on input[type=number] in
       Chromium, so the caret restore is best-effort and never fatal. */
    try { const n = el.value.length; el.setSelectionRange(n, n); } catch (e) { /* no-op */ }
  } finally {
    lvlRedrawing = false;
  }
}

function scheduleLevelRedraw() {
  if (lvlTimer) clearTimeout(lvlTimer);
  lvlTimer = setTimeout(function () { lvlTimer = null; flushLevelRedraw(); }, LVL_REDRAW_MS);
}

function go(view) {
  if (!VIEWS[view]) view = 'start';
  if (S.view !== view) { S.view = view; S.q = ''; S.limit = PAGE_SIZE; }
  render();
  try { window.scrollTo(0, 0); } catch (e) { /* no-op */ }
  setHash('#/' + view);
}

/* -------------------------------------------------------------- hash router */

/* The app owns the hash (registry nativeHashRouting: true). A hash WE wrote
   must not bounce back through applyHash, and a timer-based guard races the
   browser's own hashchange dispatch - so compare the value instead. */
let selfHash = null;
function setHash(h) {
  if (location.hash === h) return;
  selfHash = h;
  try { location.hash = h; } catch (e) { selfHash = null; }
}

function applyHash() {
  const raw = (location.hash || '').replace(/^#\/?/, '');
  const parts = raw.split('/').filter(Boolean);
  if (!parts.length) { S.view = 'start'; render(); return; }
  if (parts[0] === 'e' && parts.length >= 3) {
    const gk = parts[1];
    const k = gk + ':' + parts.slice(2).join('/');
    if (ent(k)) {
      const tab = TAB_OF[gk] || 'more';
      S.view = tab;
      if (tab === 'items' && S.iGroup !== 'all' && S.iGroup !== gk) S.iGroup = 'all';
      if (tab === 'more' && moreSections().indexOf(gk) !== -1) S.mSec = gk;
      render();
      openEntity(k);
      return;
    }
  }
  if (VIEWS[parts[0]]) { S.view = parts[0]; render(); return; }
  S.view = 'start';
  render();
}

/* ------------------------------------------------------------------ events */

document.addEventListener('click', function (ev) {
  const t = ev.target;
  if (!t || !t.closest) return;

  if (t.closest('[data-close]')) { closeSheet(); return; }

  const entBtn = t.closest('[data-ent]');
  if (entBtn) { openEntity(entBtn.getAttribute('data-ent')); return; }

  const tab = t.closest('#tabbar .tab');
  if (tab) { if (sheetOpen) closeSheet(); go(tab.getAttribute('data-view')); return; }

  const goto = t.closest('[data-goto]');
  if (goto) { if (sheetOpen) closeSheet(); go(goto.getAttribute('data-goto')); return; }

  const cattr = t.closest('[data-cattr]');
  if (cattr) { S.cAttr = cattr.getAttribute('data-cattr'); render(); return; }

  if (t.closest('[data-cplayable]')) { S.cPlayable = !S.cPlayable; render(); return; }

  const igroup = t.closest('[data-igroup]');
  if (igroup) { S.iGroup = igroup.getAttribute('data-igroup'); S.iCat = 'all'; S.iTier = 'all'; S.limit = PAGE_SIZE; render(); return; }

  const icat = t.closest('[data-icat]');
  if (icat) { S.iCat = icat.getAttribute('data-icat'); S.limit = PAGE_SIZE; render(); return; }

  const itier = t.closest('[data-itier]');
  if (itier) { S.iTier = itier.getAttribute('data-itier'); S.limit = PAGE_SIZE; render(); return; }

  const msec = t.closest('[data-msec]');
  if (msec) { S.mSec = msec.getAttribute('data-msec'); S.mCat = 'all'; S.limit = PAGE_SIZE; render(); return; }

  const mcat = t.closest('[data-mcat]');
  if (mcat) { S.mCat = mcat.getAttribute('data-mcat'); S.limit = PAGE_SIZE; render(); return; }

  if (t.closest('[data-usable]')) { S.onlyUsable = !S.onlyUsable; S.limit = PAGE_SIZE; render(); return; }

  if (t.closest('[data-more]')) { S.limit += PAGE_SIZE; refillList(); return; }

  if (t.closest('[data-clearq]')) { S.q = ''; S.limit = PAGE_SIZE; render(); return; }

  const pin = t.closest('[data-pin]');
  if (pin) {
    const on = togglePin(pin.getAttribute('data-pin'));
    pin.classList.toggle('on', on);
    pin.textContent = on ? 'Pinned' : 'Pin to my plan';
    return;
  }

  const setcls = t.closest('[data-setclass]');
  if (setcls) {
    const id = setcls.getAttribute('data-setclass');
    const now = myClass() === id ? '' : id;
    setMyClass(now);
    setcls.classList.toggle('on', !!now);
    setcls.textContent = now ? 'This is my class' : 'Play as this';
    return;
  }

  if (t.closest('[data-newprof]')) {
    const nm = window.prompt('Name this plan', 'Character ' + (Object.keys(ST.profiles).length + 1));
    if (nm) {
      const id = 'p' + Date.now().toString(36);
      ST.profiles[id] = blankProfile(nm.slice(0, 40));
      ST.active = id;
      saveState();
      render();
    }
    return;
  }
  if (t.closest('[data-renprof]')) {
    const nm = window.prompt('Rename this plan', prof().name);
    if (nm) { prof().name = nm.slice(0, 40); saveState(); render(); }
    return;
  }
  if (t.closest('[data-delprof]')) {
    if (Object.keys(ST.profiles).length > 1 && window.confirm('Delete "' + prof().name + '"?')) {
      delete ST.profiles[ST.active];
      ST.active = Object.keys(ST.profiles)[0];
      saveState();
      render();
    }
    return;
  }
});

document.addEventListener('input', function (ev) {
  const t = ev.target;
  if (!t) return;
  if (t.id === 'q') {
    S.q = t.value || '';
    S.limit = PAGE_SIZE;
    refillList();
    renderSuggest();
    return;
  }
  if (t.id === 'lvl') {
    const n = parseInt(t.value, 10);
    /* An emptied or half-typed field is not a level yet - it is left alone so a
       player clearing the box to retype is not fought mid-edit. `change` (blur)
       re-fills it from what is stored, so it can never be left disagreeing. */
    if (!isFinite(n) || n <= 0) return;
    setMyLevel(Math.min(n, 100));
    scheduleLevelRedraw();
    return;
  }
});

document.addEventListener('change', function (ev) {
  const t = ev.target;
  if (!t) return;
  if (t.id === 'prof' && ST.profiles[t.value]) {
    ST.active = t.value;
    saveState();
    render();
    return;
  }
  if (t.id === 'clsSel') { setMyClass(t.value); render(); return; }
  if (t.id === 'lvl') { flushLevelRedraw(); return; }
});

document.addEventListener('keydown', function (ev) {
  if (ev.key === 'Escape' && sheetOpen) closeSheet();
});

window.addEventListener('hashchange', function () {
  if (selfHash !== null && location.hash === selfHash) { selfHash = null; return; }
  selfHash = null;
  if (!S.booted) return;
  if (sheetOpen) {
    const sh = $('#sheet');
    if (sh) sh.hidden = true;
    sheetOpen = false;
    try { document.body.style.overflow = ''; } catch (e) { /* no-op */ }
  }
  applyHash();
});

/* -------------------------------------------------------------------- boot */

function fetchJson(path) {
  return fetch(path, { cache: 'no-cache' }).then(function (r) {
    if (!r.ok) throw new Error(path + ' -> HTTP ' + r.status);
    return r.json();
  });
}

function boot() {
  ST = loadState();
  const a = app();
  if (a) a.innerHTML = '<div class="boot">Loading Path of Exile 2 data...</div>';

  fetchJson('/island/apps/poe2/data/meta.json').then(function (meta) {
    S.meta = meta;
    const wiki = meta.wiki || {};
    S.gmeta = Object.keys(wiki).map(function (k) {
      return {
        key: k,
        title: wiki[k].title || k,
        nameField: wiki[k].nameField || 'name',
        file: wiki[k].file || (k + '.json')
      };
    });
    if (!S.gmeta.length) throw new Error('meta.json has no wiki group map');
    for (const d of S.gmeta) S.gmap[d.key] = d;
    return Promise.all(S.gmeta.map(function (d) {
      return fetchJson('/island/apps/poe2/data/' + d.file).then(function (rows) {
        S.groups[d.key] = Array.isArray(rows) ? rows : [];
      });
    }));
  }).then(function () {
    for (const d of S.gmeta) {
      for (const e of S.groups[d.key]) {
        const k = keyOf(d.key, e.id);
        S.byId[k] = e;
        const nm = String(nameOf(e, d.key) || '').toLowerCase();
        if (nm && !S.byName[nm]) S.byName[nm] = k;
      }
    }
    buildIndex();
    const pill = $('#patchPill');
    if (pill && S.meta.pulledAtVersion) pill.textContent = 'Patch ' + S.meta.pulledAtVersion;
    const foot = $('#footNote');
    if (foot && S.meta.attribution) foot.textContent = S.meta.attribution;
    renderStageBanner();
    S.booted = true;
    applyHash();
    warmSprites();
  }).catch(function (err) {
    const el = app();
    if (el) {
      el.innerHTML = '<div class="boot err">Could not load the Path of Exile 2 dataset.<br />' +
        esc(err && err.message ? err.message : String(err)) +
        '<br /><span class="small faint">If you are offline and this app was never opened online, ' +
        'there is nothing cached yet.</span></div>';
    }
  });
}

/* ------------------------------------------------------ offline sprite warm */
/* Every entity icon is a LOCAL file under sprites/ (meta.coreIcons:
   withLocalIcon 1810 of 1810), but LOCAL is not CACHED. The shell's service
   worker stores an image the moment something requests it and not a moment
   before, so without this an installed PWA holds only the icons the viewer
   already scrolled past and every other one draws the '?' tile offline.

   registry.spriteWarm (see README.md checklist line 3) gives this route its
   own cache bucket, cache-first and exempt from the shared image LRU's
   2,000-ENTRY cap - which this route needs on the count alone: 1,820 sprite
   files would fill 91% of a cap it shares with seven other routes. Declaring
   the bucket is only HALF of it; it changes WHERE a fetched sprite lands and
   pre-fetches nothing. This is the other half: the app names the files, the
   worker does the caching.

   The APP owns the list because only the app has data/*.json parsed - and the
   walk below is why: skill gems carry a SECOND local icon (skillIcon, the
   action-bar art) and ascendancy portraits are nested inside their parent
   class, so a naive top-level `icon` sweep would miss both and leave those
   holes offline.

   Cost: about 1,811 files / 31 MB (meta.sprites.bytes), fetched 24 at a time
   in the background and only once per dataset stamp. That is the largest warm
   of any route in the app and it is deliberate: they are all CORE entity
   icons, so a partial warm is a partial app offline. The post is delayed past
   first paint so it never competes with the icons on screen. */

/* Two path shapes reach us and both must reduce to a bare filename:
     standalone  "/island/apps/poe2/sprites/fireball-skill-icon.png"     (what data/*.json ships)
     mounted     "/island/apps/poe2/sprites/..."         (assemble rewrites it)
   Strip through the LAST "sprites/" with a greedy .*, which covers both and
   any future mount prefix. A sprite filename can never contain a slash, so a
   result that still does is quarantined into `unresolved` and never posted - a
   new path shape then shows up as an empty warm rather than as ~1,800
   silently-404ing requests on every page load. */
const SPRITE_BASE_RE = /^.*\/?sprites\//;
function spriteFile(p) { return String(p == null ? '' : p).replace(SPRITE_BASE_RE, ''); }

let SPRITE_WARM = null;
function spriteWarmPayload() {
  if (SPRITE_WARM) return SPRITE_WARM;
  const files = new Set(), bad = new Set();
  const add = function (p) {
    if (!p) return;
    const f = spriteFile(p);
    if (!f || f.indexOf('/') !== -1) { bad.add(String(p)); return; }
    files.add(f);
  };
  for (const d of S.gmeta) {
    for (const e of (S.groups[d.key] || [])) {
      if (!e) continue;
      add(e.icon);
      add(e.skillIcon);
      for (const a of (e.ascendancies || [])) add(a && a.icon);
    }
  }
  const m = S.meta || {};
  SPRITE_WARM = {
    files: Array.from(files),
    unresolved: Array.from(bad),
    // Changes whenever the dataset is re-pulled, which is what re-warms the
    // new sprites after a patch.
    stamp: (m.pulledAt || '') + ':' + ((m.sprites && m.sprites.onDisk) || 0) + ':' + files.size
  };
  return SPRITE_WARM;
}

/* boot()'s data fetch and the service-worker handshake race each other, so
   BOTH sides call this and it no-ops until both halves are ready. Whichever
   finishes last is the one that actually schedules the post. */
let SW_TARGET = null;
let warmPosted = false;
function warmSprites() {
  if (!SW_TARGET || !S.booted || warmPosted) return;
  warmPosted = true;
  // Past first paint on purpose: 1,811 background requests must never race the
  // handful of icons the viewer is actually looking at.
  setTimeout(function () {
    try {
      const p = spriteWarmPayload();
      if (!p.files.length) return;
      SW_TARGET.postMessage({ type: 'warm-sprites', stamp: p.stamp, tiers: [['icons', p.files]] });
    } catch (e) { /* no-op */ }
  }, 1500);
}
if ('serviceWorker' in navigator) {
  /* This app REGISTERS nothing - the shell owns exactly one worker (see the
     PORT NOTES at the top of this file). It only waits for whichever worker
     already controls this page. Served standalone with no worker at all,
     `ready` never settles and this is simply a no-op. */
  navigator.serviceWorker.ready.then(function (reg) {
    SW_TARGET = navigator.serviceWorker.controller || (reg && reg.active);
    warmSprites();
  }).catch(function () { /* no-op */ });
}

if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', boot);
else boot();
