/* Path of Exile 2 Companion - the Builds tab (tool depth L1, curated list).
 *
 * THE SEAM. js/app.js's renderBuilds() hands this file the whole tab if
 * window.POE2_BUILDS.render exists and does not throw, and renders its own
 * fallback if either is untrue. Nothing in app.js was edited to add this file:
 * it is one <script> tag after app.js and one registry `scripts` entry. Both
 * are classic scripts, so every helper app.js declares at top level (S, ST,
 * esc, ent, iconHtml, searchHtml, myLevel, ovGet, render, ...) is in scope here
 * by name. Loading order is what makes that true - this file must come AFTER
 * app.js in index.html.
 *
 * WHERE THE CONTENT COMES FROM, and what is deliberately absent:
 *
 *  - The curation is data/builds.json, generated by tools/build_builds.mjs from
 *    tools/builds-curated.json plus data/<group>.json. THIS FILE HAND-WRITES NO
 *    GAME CONTENT. There is no build, no gem, no item and no reason typed in
 *    here; there is not even a game NUMBER. Every string a player reads about
 *    the game comes out of the data, and every number is read off the same
 *    entity record the Items tab reads (S.byId), which is why the two screens
 *    cannot print different levels for the same item. validate.mjs group X
 *    asserts both halves of that: no number in builds.json, and no dataset id
 *    or name as a literal in this file.
 *
 *  - No scoring, no ranking, no percentages. Path of Exile 2 publishes no
 *    match-outcome data, so an L1 curated list is the honest rung
 *    (NEW-GAME-TEMPLATE section 9, decision rule step 1). The ruling sentence
 *    that says so on the tab is itself read from the data.
 *
 * OWNERSHIP GATE (what L1 requires): a build is gated on three things the
 * player states, all of them living in the app's own localStorage blob under
 * the existing key - character level, chosen class, and which of the build's
 * pieces they actually have. The "have" flags go through app.js's sparse
 * override layer (ovGet/ovSet on group 'have'), so a false is stored as a
 * deleted key rather than as noise, and the whole thing rides the profile
 * system that was already there - a second character gets its own answers.
 * An unavailable build is never hidden: it says what is missing.
 */
'use strict';

(function () {
  /* ---------------------------------------------------------------- state */

  var BD = null;           // parsed data/builds.json
  var loadState = 'idle';  // idle | loading | ready | failed
  var loadErr = '';
  var expanded = {};       // buildId -> true, survives a re-render
  var filter = 'all';      // all | mine | ready

  var HAVE = 'have';       // override-layer group name for ownership flags

  function keyFor(p) { return p.group + ':' + p.id; }
  function hasPick(p) { return ovGet(prof(), HAVE, keyFor(p), false) === true; }
  function setHave(k, v) { ovSet(HAVE, k, v === true); }

  /* "Nothing is marked" and "you own none of it" are the same data and very
     different sentences. On a profile the player has never ticked anything on,
     saying a build is short 10 pieces reads as a verdict on their stash rather
     than as an empty form - so the two states are separated everywhere. */
  function touchedAnything() {
    if (!BD) return false;
    for (var i = 0; i < BD.builds.length; i++) {
      var ps = BD.builds[i].picks || [];
      for (var j = 0; j < ps.length; j++) if (hasPick(ps[j])) return true;
    }
    return false;
  }

  /* --------------------------------------------------------------- loader */

  function load() {
    if (loadState !== 'idle') return;
    loadState = 'loading';
    fetch('/island/apps/poe2/data/builds.json', { cache: 'no-cache' }).then(function (r) {
      if (!r.ok) throw new Error('HTTP ' + r.status);
      return r.json();
    }).then(function (j) {
      if (!j || !Array.isArray(j.builds)) throw new Error('builds.json carries no builds array');
      BD = j;
      loadState = 'ready';
      /* Only re-render if the player is still looking at this tab - calling
         render() from a background load would yank them off whatever they
         navigated to while it was in flight. */
      if (S.view === 'builds') render();
    }).catch(function (e) {
      loadState = 'failed';
      loadErr = e && e.message ? e.message : String(e);
      if (S.view === 'builds') render();
    });
  }

  /* ------------------------------------------------------------ resolution */

  /* Every pick resolves through the app's own entity index, so a build row and
     an Items row are literally reading the same object. Returns null for an id
     the current dataset no longer carries - the generator makes that
     impossible at build time, but a stale cached builds.json against a fresh
     dataset is exactly the case where a runtime guard earns its keep. */
  function recOf(p) { return ent(keyFor(p)); }

  function levelOfGate(b) {
    if (!b.levelGate) return null;
    var e = ent(b.levelGate.group + ':' + b.levelGate.id);
    if (!e || typeof e.requiredLevel !== 'number') return null;
    return e.requiredLevel;
  }

  function classRec(b) { return b.class ? ent('classes:' + b.class) : null; }

  function ascRec(b) {
    var c = classRec(b);
    if (!c || !b.ascendancy) return null;
    var list = c.ascendancies || [];
    for (var i = 0; i < list.length; i++) if (list[i].id === b.ascendancy) return list[i];
    return null;
  }

  /* One place decides whether a build is ready, and the same object feeds the
     status line, the chip and the filter - so a build can never be filtered as
     ready and then described as blocked. */
  function statusOf(b) {
    var picks = b.picks || [];
    var known = [], missing = [], dead = [];
    for (var i = 0; i < picks.length; i++) {
      var r = recOf(picks[i]);
      if (!r) { dead.push(picks[i]); continue; }
      known.push(picks[i]);
      if (!hasPick(picks[i])) missing.push(picks[i]);
    }
    var gateLvl = levelOfGate(b);
    var lvl = myLevel();
    var mine = myClass();
    return {
      picks: picks,
      known: known,
      missing: missing,
      dead: dead,
      owned: known.length - missing.length,
      gateLevel: gateLvl,
      levelOk: gateLvl === null ? true : lvl >= gateLvl,
      classChosen: !!mine,
      classMatch: !b.class || !mine || mine === b.class,
      ready: (gateLvl === null || lvl >= gateLvl) && missing.length === 0 && dead.length === 0,
    };
  }

  /* ------------------------------------------------------------- rendering */

  function statusChip(st, touched) {
    if (st.dead.length) return '<span class="bld-chip bad">Needs a refresh</span>';
    if (st.ready) return '<span class="bld-chip ok">Ready to play</span>';
    if (!touched) return '<span class="bld-chip">Nothing marked yet</span>';
    if (!st.levelOk) return '<span class="bld-chip warn">Level ' + esc(st.gateLevel) + '</span>';
    return '<span class="bld-chip warn">' + esc(st.missing.length) + ' still to find</span>';
  }

  /* The plain sentence that says WHY a build is not available. L1's rule: never
     hide it, never make the player work it out from a chip. */
  function statusLine(b, st, touched) {
    var bits = [];
    if (!st.dead.length && !touched) {
      var lvlBit = st.gateLevel === null
        ? 'Nothing in it publishes a level requirement.'
        : (st.levelOk
          ? 'You are past the level it needs (' + st.gateLevel + ').'
          : 'It is fully assembled at level ' + st.gateLevel + ', and you are level ' + myLevel() + '.');
      return 'You have not marked anything as owned yet, so nothing here is checked off. ' +
        'Open it and tap Mark on each piece you already have. ' + lvlBit;
    }
    if (st.dead.length) {
      bits.push('This build names ' + st.dead.length + ' entry ' +
        (st.dead.length === 1 ? 'that is' : 'that are') +
        ' not in the dataset this app has loaded, so it cannot be checked. Reload the app to pick up the current data.');
      return bits.join(' ');
    }
    if (!st.levelOk) {
      bits.push('Not yet usable: you are level ' + myLevel() + ' and the last piece of this build needs level ' +
        st.gateLevel + '.');
    }
    if (st.missing.length) {
      var names = st.missing.slice(0, 3).map(function (p) {
        var r = recOf(p);
        return r ? nameOf(r, p.group) : p.id;
      });
      bits.push('Still to find: ' + names.join(', ') +
        (st.missing.length > names.length ? ' and ' + (st.missing.length - names.length) + ' more' : '') + '.');
    }
    if (b.class && st.classChosen && !st.classMatch) {
      var c = classRec(b);
      bits.push('It is written for the ' + (c ? nameOf(c, 'classes') : b.class) +
        ', and you have a different class saved on this plan.');
    }
    if (!bits.length) {
      bits.push('You have marked every piece of this build as owned' +
        (st.gateLevel === null ? '.' : ' and you are past level ' + st.gateLevel + '.'));
    }
    return bits.join(' ');
  }

  function pickRow(p) {
    var r = recOf(p);
    var k = keyFor(p);
    if (!r) {
      return '<div class="bld-pick missing"><span class="bld-pb">' +
        '<span class="bld-pr">' + esc(p.role) + '</span>' +
        '<span class="bld-pn">' + esc(p.id) + '</span>' +
        '<span class="bld-pw">This entry is not in the dataset the app has loaded. It was in the dataset the build list was generated from, so the two are out of step.</span>' +
        '</span></div>';
    }
    var have = hasPick(p);
    return '<div class="bld-pick' + (have ? ' have' : '') + '">' +
      '<button class="bld-po" data-ent="' + esc(k) + '" aria-label="Open">' +
        iconHtml(r, 44) +
      '</button>' +
      '<span class="bld-pb">' +
        '<span class="bld-pr">' + esc(p.role) + (p.main ? ' &middot; main' : '') + '</span>' +
        '<button class="bld-pn" data-ent="' + esc(k) + '">' + esc(nameOf(r, p.group)) + '</button>' +
        '<span class="bld-pc">' + rowChips(p.group, r) + '</span>' +
        '<span class="bld-pw">' + esc(p.why) + '</span>' +
      '</span>' +
      '<button class="bld-have' + (have ? ' on' : '') + '" data-bhave="' + esc(k) + '" ' +
        'aria-pressed="' + (have ? 'true' : 'false') + '">' + (have ? 'Have it' : 'Mark') + '</button>' +
      '</div>';
  }

  function buildCard(b, touched) {
    var st = statusOf(b);
    var open = expanded[b.id] === true;
    var c = classRec(b);
    var a = ascRec(b);

    var h = '<div class="bld-card' + (st.ready ? ' ready' : '') + '">';

    h += '<button class="bld-head" data-bexp="' + esc(b.id) + '" aria-expanded="' + (open ? 'true' : 'false') + '">';
    if (c) h += iconHtml(c, 44);
    h += '<span class="bld-hb">' +
      '<span class="bld-hn">' + esc(b.name) + '</span>' +
      '<span class="bld-hs">' + esc(b.forWho) + '</span>' +
      '<span class="bld-hc">' + statusChip(st, touched) +
        (c ? '<span class="bld-chip">' + esc(nameOf(c, 'classes')) + '</span>' : '') +
        (a ? '<span class="bld-chip">' + esc(a.name) + '</span>' : '') +
        '<span class="bld-chip faintchip">' + (touched ? esc(st.owned) + ' of ' + esc(st.known.length) + ' owned' : esc(st.known.length) + ' pieces') + '</span>' +
      '</span></span>';
    h += '<span class="bld-caret">' + (open ? '&#9650;' : '&#9660;') + '</span>';
    h += '</button>';

    h += '<div class="bld-status">' + esc(statusLine(b, st, touched)) + '</div>';

    if (!open) { h += '</div>'; return h; }

    /* The three fixed sections, same headings as every entity page in the app
       and in the vault wiki (NEW-GAME-TEMPLATE section 8). */
    var rows = [['What it is', b.beginner.whatItIs],
                ['Why it matters', b.beginner.whyItMatters],
                ['When to use it', b.beginner.whenToUseIt]];
    h += '<div class="beg">';
    for (var i = 0; i < rows.length; i++) {
      if (!rows[i][1]) continue;
      h += '<p class="bh">' + esc(rows[i][0]) + '</p><p class="bp">' + esc(rows[i][1]) + '</p>';
    }
    h += '</div>';

    if (b.levelGate && st.gateLevel !== null) {
      var g = ent(b.levelGate.group + ':' + b.levelGate.id);
      h += '<div class="bld-gate">Fully assembled at level ' + esc(st.gateLevel) +
        ', which is what <b>' + esc(nameOf(g, b.levelGate.group)) + '</b> asks for. ' +
        'Everything else in the list can be used before that.</div>';
    } else {
      h += '<div class="bld-gate">Nothing in this build publishes a level requirement, so there is no level to wait for.</div>';
    }

    h += '<div class="bld-picks">';
    for (var j = 0; j < b.picks.length; j++) h += pickRow(b.picks[j]);
    h += '</div>';

    h += '<div class="row wrap g8 mt8">' +
      '<button class="tbtn" data-ball="' + esc(b.id) + '">Mark every piece as owned</button>' +
      '<button class="tbtn" data-bnone="' + esc(b.id) + '">Clear them</button>' +
      (b.class ? '<button class="tbtn" data-ent="' + esc('classes:' + b.class) + '">Open the class</button>' : '') +
      '</div>';

    h += '</div>';
    return h;
  }

  function charCard() {
    var h = '<h3 class="sh">Your character</h3><div class="card">';
    h += '<div class="lvlctl"><label for="lvl" class="small muted">Character level</label>' +
      '<input id="lvl" type="number" min="1" max="100" inputmode="numeric" value="' + esc(myLevel()) + '" />' +
      '<span class="small faint">Also filters every list on the other tabs to what you can equip.</span></div>';

    var cls = (S.groups.classes || []).filter(function (c) { return c.playable !== false; });
    if (cls.length) {
      h += '<div class="lvlctl" style="margin-top:12px"><label for="clsSel" class="small muted">Class</label>' +
        '<select id="clsSel" class="profsel"><option value="">Not chosen</option>' +
        cls.map(function (c) {
          return '<option value="' + esc(c.id) + '"' + (myClass() === c.id ? ' selected' : '') +
            '>' + esc(c.name) + '</option>';
        }).join('') + '</select></div>';
    }

    h += '<div class="lvlctl" style="margin-top:12px"><label for="prof" class="small muted">Saved plan</label>' +
      '<select id="prof" class="profsel">' + Object.keys(ST.profiles).map(function (id) {
        return '<option value="' + esc(id) + '"' + (id === ST.active ? ' selected' : '') +
          '>' + esc(ST.profiles[id].name) + '</option>';
      }).join('') + '</select>' +
      '<button class="tbtn" data-newprof>New</button>' +
      '<button class="tbtn" data-renprof>Rename</button>' +
      (Object.keys(ST.profiles).length > 1 ? '<button class="tbtn danger" data-delprof>Delete</button>' : '') +
      '</div>';
    h += '<p class="small faint" style="margin:10px 0 0">What you own is saved per plan, so a second character starts with an empty sheet instead of inheriting the first one\'s answers.</p>';
    h += '</div>';
    return h;
  }

  function pinnedCard() {
    var pinKeys = prof().pins.filter(function (k) { return !!ent(k); });
    var h = '<h3 class="sh">Pinned (' + pinKeys.length + ')</h3>';
    if (!pinKeys.length) {
      return h + '<div class="card muted small">Nothing pinned yet. Open any gem, unique or currency item ' +
        'and tap "Pin to my plan" to park it here while you work out a build of your own.</div>';
    }
    var maxLvl = 0, counted = 0;
    for (var i = 0; i < pinKeys.length; i++) {
      var e = ent(pinKeys[i]);
      if (e && typeof e.requiredLevel === 'number') {
        counted++;
        if (e.requiredLevel > maxLvl) maxLvl = e.requiredLevel;
      }
    }
    if (counted) {
      h += '<div class="card tight"><div class="fresh">' +
        '<span>Highest level requirement <b>' + esc(maxLvl) + '</b></span><span class="faint">&middot;</span>' +
        '<span>' + counted + ' of ' + pinKeys.length + ' publish one</span></div>' +
        '<p class="small faint" style="margin:6px 0 0">The level this set of pins is fully usable at, taken from ' +
        'the entries that publish a required level. Entries with none are not counted.</p></div>';
    }
    for (var j = 0; j < pinKeys.length; j++) {
      var k = pinKeys[j], en = ent(k), gk = groupOf(k);
      h += '<button class="rowcard" data-ent="' + esc(k) + '">' + iconHtml(en, 44) +
        '<span class="rb"><span class="rn">' + esc(nameOf(en, gk)) + '</span>' +
        '<span class="rm">' + esc(groupTitle(gk)) + ' &middot; ' + esc(catOf(gk, en)) + '</span></span>' +
        '<span class="rc">' + rowChips(gk, en) + '</span></button>';
    }
    return h;
  }

  function freshCard() {
    var m = S.meta || {};
    return '<div class="card"><div class="fresh">' +
      '<span>Data pulled <b>' + esc(prettyDate(m.pulledAt)) + '</b></span><span class="faint">&middot;</span>' +
      '<span>Reflects patch <b>' + esc(m.pulledAtVersion || 'unknown') + '</b></span></div>' +
      '<p class="small muted" style="margin:8px 0 0">Path of Exile 2 is in Early Access and patches land every ' +
      'one to three weeks. Every build below describes the patch named above and nothing later.</p></div>';
  }

  function listSection() {
    if (loadState === 'loading' || loadState === 'idle') {
      return '<h3 class="sh">Starter builds</h3><div class="mount-slot">Loading the build list...</div>';
    }
    if (loadState === 'failed') {
      return '<h3 class="sh">Starter builds</h3><div class="mount-slot">The build list could not be loaded (' +
        esc(loadErr) + '). Everything else on this tab still works, and the other tabs are unaffected.</div>';
    }

    var all = BD.builds;
    var touched = touchedAnything();
    var mineId = myClass();
    var shown = all.filter(function (b) {
      if (filter === 'mine') return !!mineId && b.class === mineId;
      if (filter === 'ready') return statusOf(b).ready;
      return true;
    });

    var h = '<h3 class="sh">Starter builds (' + all.length + ')</h3>';
    h += '<div class="ruling">' + esc(BD.ruling) + '</div>';

    h += '<div class="chiprow">' +
      '<button class="fbtn' + (filter === 'all' ? ' on' : '') + '" data-bfilter="all">Every build</button>' +
      '<button class="fbtn' + (filter === 'mine' ? ' on' : '') + '" data-bfilter="mine">For my class</button>' +
      '<button class="fbtn' + (filter === 'ready' ? ' on' : '') + '" data-bfilter="ready">Ready to play</button>' +
      '</div>';

    if (!shown.length) {
      if (filter === 'mine') {
        h += '<div class="mount-slot">' + (mineId
          ? 'No build in this list is written for the class saved on this plan yet. Tap "Every build" to see the rest.'
          : 'Choose a class above and this filter will show the builds written for it.') + '</div>';
      } else {
        h += '<div class="mount-slot">No build is fully assembled on this plan yet. ' +
          'Open one and mark the pieces you already have.</div>';
      }
      return h;
    }

    for (var i = 0; i < shown.length; i++) h += buildCard(shown[i], touched);
    return h;
  }

  /* ------------------------------------------------------------------ tab */

  function renderTab() {
    if (loadState === 'idle') load();

    var h = '<div class="view">';
    h += searchHtml('Search anything while you plan');
    h += '<h2 class="vh">Build planner</h2>';
    h += freshCard();
    h += listSection();
    h += charCard();
    h += pinnedCard();
    h += '</div>';
    return h;
  }

  /* --------------------------------------------------------------- events */

  /* app.js registered its own document click handler first. It returns early
     only on attributes it recognises and never calls stopPropagation, so these
     attributes - which it has never heard of - reach this handler untouched.
     The one shape that must be avoided is nesting a control INSIDE an element
     carrying data-ent, because app.js would open the entity sheet instead; the
     pick row is a plain container with the two buttons as siblings for exactly
     that reason. */
  document.addEventListener('click', function (ev) {
    var t = ev.target;
    if (!t || !t.closest) return;

    var f = t.closest('[data-bfilter]');
    if (f) { filter = f.getAttribute('data-bfilter'); if (S.view === 'builds') render(); return; }

    var x = t.closest('[data-bexp]');
    if (x) {
      var id = x.getAttribute('data-bexp');
      expanded[id] = !expanded[id];
      if (S.view === 'builds') render();
      return;
    }

    var hv = t.closest('[data-bhave]');
    if (hv) {
      var k = hv.getAttribute('data-bhave');
      setHave(k, ovGet(prof(), HAVE, k, false) !== true);
      if (S.view === 'builds') render();
      return;
    }

    var ba = t.closest('[data-ball]');
    if (ba) { setAll(ba.getAttribute('data-ball'), true); return; }

    var bn = t.closest('[data-bnone]');
    if (bn) { setAll(bn.getAttribute('data-bnone'), false); return; }
  });

  function setAll(buildId, val) {
    if (!BD) return;
    var b = null;
    for (var i = 0; i < BD.builds.length; i++) if (BD.builds[i].id === buildId) b = BD.builds[i];
    if (!b) return;
    for (var j = 0; j < b.picks.length; j++) setHave(keyFor(b.picks[j]), val);
    if (S.view === 'builds') render();
  }

  window.POE2_BUILDS = { render: renderTab };
}());
